### ISSUE TITLE
Harder to tap icons and menu icons in playlist view

### ISSUE THREAD

**Issue by duracell80** [moode-player/moode#109]
I made a quick comparison between 6.4 and 6.5 on a regression of ease of use on the 7" touchscreens. It could be that the duration being missing gives a smaller hit area. I think though even with duration the area is now a lot smaller to tap and more frustrating. The ellipsis menu itself is smaller too, along with a few other of the icons such as shuffle, favorite, cover view toggle.

https://www.youtube.com/watch?v=JNFgZtbPHU8

**Comment by moodeaudio** [comment]
Run the SQL command below and then Menu, Refresh. Post back the viewport sizes that are reported for both Pixel aspect ratio = Default and Pixel aspect ratio = Square.  You'll need a reboot when changing this option.

My Touch which for years reported only 799x479 if memory serves me correctly now reports the following:
Pixel aspect ratio = Default:  998x598
Pixel aspect ratio = Square:  998x553

Couple things:
1. There is no media query for 998x553 in r652 which is a bug.
2. When loading updated CSS I've found that I almost always have to clear the Local UI Browser cache before the changes are picked up. There is a CLEAR button on System Config for this.

```
sudo sqlite3 /var/local/www/db/moode-sqlite3.db "update cfg_system set value='viewport' where param='pkgid_suffix'"
```

To turn off the viewport popup 
```
set value=''
```
