### ISSUE TITLE
Stream on other port as 80 not working?

### ISSUE THREAD

**Issue by tiborepcek** [moode-player/moode#133]
Hi and thank you for MoOde Player.

I would like to ask, why stream on URL https://stream.funradio.sk:18443/fun64.mp3 does not work on MoOde Player on RPi 3 B+, but in web browser it works.

All other streams on port 80 work just fine on MoOde Player on RPi 3 B+.

I use this configuration:

```
moOde release		= 6.5.2 2020-05-03
Raspbian OS		= 10.3
Linux kernel		= 4.19.115-v7+ #1305
Platform		= Pi-3B+ 1GB v1.3
Architecture		= armv7l (32-bit)
```

Any advice?

Thank you.

**Comment by moodeaudio** [comment]
I can repro and it looks like some kind of certificate issue. The error from MPD is below. If you can view the cert in your Browser then maybe try posting the issue to MPD or Raspbian maintainers. 

```
Failed to decode https://stream.funradio.sk:18443/fun64.mp3; CURL failed: server certificate verification failed. CAfile: none CRLfile: none
```

**Comment by moodeaudio** [comment]
Most likely not a moOde issue
https://github.com/MusicPlayerDaemon/MPD/issues/887
