### ISSUE TITLE
Move radio artwork out of /var/www source tree

### ISSUE THREAD

**Issue by bitkeeper** [moode-player/moode#134]
Maybe with all the changes to the radio stuff, it is good moment to move the radio artwork out of the source tree (`/var/www`) to a datalocation in  /var/local ? 

This is more inline with the way album art is implemented and leaves a clear source tree. 
To minimize impact the nginx location directive can be mapped to the same location `/images/radio-logos`.

**Comment by bitkeeper** [comment]
The new radio export function makes harder to move it lateron due the full path in the zipfile.

**Comment by moodeaudio** [comment]
Yes logos and thumbs can be moved to /var/local/imagesw

I'm not sure how to tell the zip util to use other than the full paths.

**Comment by moodeaudio** [comment]
PR was merged :-)
