### ISSUE TITLE
how do you provide cover art over a http stream to mdp?

### ISSUE THREAD

**Issue by lachlan-00** [moode-player/moode#137]
Hey, i know this isn't really specific to moode but i really like using moode with my ampache server and was wondering if you could help get the art displaying?

I play these stream urls to the mpd server
https://my.ampache.server/play/ssid/%ampachesessionID%/type/song/oid/105444/uid/2/name/KoRN%20-%20Counting.mp3

that plays totally fine, just without the art.
![image](https://user-images.githubusercontent.com/1305249/83840173-3f018b00-a741-11ea-9063-470a44735127.png)

The art exists and even if it didn't i'd like to provide a backup/fallback image in the server.
![image](https://user-images.githubusercontent.com/1305249/83840282-7d974580-a741-11ea-91bb-8da86d990423.png)

I'd really like to make the changes to Ampache to benefit everyone but i'm just not really sure how players like moode use/check for images.

**Comment by lachlan-00** [comment]
secondarily can i provide a server name to the client?
![image](https://user-images.githubusercontent.com/1305249/83840907-09f63800-a743-11ea-8c12-968d4f013efc.png)

**Comment by lachlan-00** [comment]
sorry for the spam but it would also be cool for the playlist to load the details before the track is played
![image](https://user-images.githubusercontent.com/1305249/83843897-52185900-a749-11ea-9818-0557ac664e03.png)

**Comment by moodeaudio** [comment]
Our project only provides support for moOde's built in WebUI.

**Comment by lachlan-00** [comment]
This question is about how to get URLs that display things in the moode webUI but okay
