### ISSUE TITLE
Load available mpd versions from config file

### ISSUE THREAD

**Issue by bitkeeper** [moode-player/moode#141]
When the use MPD get gets a version bump, the source snd-config.php needs to be changed .

Is it an idea to load the available versions of MPD from a config file ?
This will decouple the available mpd version from the snd-config. Also makes it easier to tinker arround with multiple mpd versions.

For example /var/local/www/mpdversions.cfg, with the content:
```
# This config contains the selectable mpd versions for moOde
0.21.24;0.21.24 (Default)
0.22~git;0.22~git (Test)
```
Each line contains two part Separated by a ';'.  The first is the version for binary name and the second a label. 
Lines with # or empty are ignored.

**Comment by moodeaudio** [comment]
Thats a good idea. 

The config file should prolly be named mpd_versions.conf rather than mpdversion.cfg

**Comment by bitkeeper** [comment]
Renamed config file to mp_versions.conf in PR #142.

**Comment by moodeaudio** [comment]
PR accepted.
