### ISSUE TITLE
build_recipe_v2.23.txt uses stale libupnpp-samples code

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#143]
With this recipe, building upmpdcli and the libraries it depends on succeeded on a moOde 6.5.2 player but when I get to this step in the upmpdcli build section

```
5. upexplorer

NOTE: This also installs a bunch of other utils

sudo cp -r ./moode/other/libupnppsamples-code/ ./
cd libupnppsamples-code
sudo ./autogen.sh
sudo ./configure
sudo make
sudo make install
cd ~
sudo rm -rf ./libupnppsamples-code
```
I experience an error in compiling typedservice.cpp

```
src/typedservice.cpp:78:5: error: ‘sleep’ was not declared in this scope
     sleep(1000);
     ^~~~~
```
The build fails, and all the sample utilities in /usr/local/bin are the old ones, dated Feb 17, which were shipped with moOde 6.5.2.

Looking at Jean-Francois's new [https://framagit.org/medoc92/libupnpp-samples](https://framagit.org/medoc92/libupnpp-samples) I see that a year ago he has commits to "Fix a few things necessitated by libupnpp removing...."

I downloaded current master for the libupnpp-samples repo and built/installed all the utilities without error. Now all the sample utilities in /usr/local/bin are dated today.

In particular
```
-rwxr-xr-x 1 root root   1718220 Jun 28 15:45 upexplorer
```

**Comment by moodeaudio** [comment]
Ok, looks good. We can go ahead with latest 1.4.12 upmpdcli for moOde 6.6.0 :-)
