### ISSUE TITLE
UPnP problems

### ISSUE THREAD

**Issue by mikesturg** [moode-player/moode#144]
Hi. I'm new to Moode (6.5.2) which I have installed on my newly acquired Pi 4B. I've added (and configured) the Audiophonics DAC I-Sabre ES9038Q2M. One of my music sources is Google Play Music - soon to be You Tube Music. I followed the configuration in Moode as described, and I have BubbleUPnP on my android phone. Apart from a relatively long period of time for BubbleUpnP to connect to Moode UPNP (anything from around 10 secs to 30 secs), I only seem to be able to play a single track. Once I switch to accessing a playlist or Album in BubbleUPnP, I cannot get any playback in Moode.

My Google Play Music account has been configured in both BubbleUPnP and the Moode Player. 

There's a raft of settings in both these apps, and I've not really got any idea what the problem(s) is.

Any ideas/help greatly appreciated.

**Comment by moodeaudio** [comment]
Your best bet is to post the issue in the support section of the Moode Forum. I don't really use UPnP and so can't offer any help.
