### ISSUE TITLE
Edit station invalid displayed name causes no image to be displayed when playing the station

### ISSUE THREAD

**Issue by TheMetalHead** [moode-player/moode#148]
In the 'Edit Station' tab it is possible to enter some invalid characters in the 'Name (displayed) field.
This causes the image to not be displayed when the station is being played.
The two characters tested so far are a leading space and the vertical bar |
Normally the displayed name is set the same as the station name but it can be edited by the user to whatever is required.
The station name and displayed name should both be parsed for any invalid characters and removed if any have been found.

**Comment by moodeaudio** [comment]
Add to TODO list.
