### ISSUE TITLE
Audio scrobbler won't scrobble when using UPNP Renderer/Tidal

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [moode-player/moode#15]
Is it an attended behavior?

The userid and password in the audio scrobbler config screen must be the same as my last.fm login username and password? Or do I have to create API keys?

Do I have to install some system libraries for this functionality to work?

Where are the concerned logs located and what should I look for in order to debug this functionality?

**Comment by moodeaudio** [comment]
Hi,

Your best bet is to post this question in the moOde Forum in the support section. There are several users that are using Last.FM with moOde and maybe they can help you out :-)

http://moodeaudio.org/forum

-Tim

**Comment by Yonn-Trimoreau** [comment]
Thank you Tim.

http://moodeaudio.org/forum/showthread.php?tid=905
