### ISSUE TITLE
Volume can be scrolled using mouse wheel below zero to -1

### ISSUE THREAD

**Issue by TheMetalHead** [moode-player/moode#150]
Moode v6.7.0

There is an issue when using the mouse wheel to change the volume.

To re-create the issue select a stream to play, set the volume to below 5 and then using the mouse wheel, quickly scroll down to zero. The volume will go to -1.
Clicking on the + and - indicators are ok.

**Comment by moodeaudio** [comment]
Thats odd. I don't have a mouse to be able to repro but try to verify what the MPD volume is when the knob shows -1.

mpc volume

**Comment by TheMetalHead** [comment]
Knob at 4% mpc volume shows 4%
Scroll the knob to -1 mpc volume shows 0%

**Comment by bitkeeper** [comment]
Can reproduce with both Firefox and Chrome.

**Comment by bitkeeper** [comment]
@TheMetalHead the issues should be fixed in upcoming release 6.7.1.

**Comment by moodeaudio** [comment]
PR to address this has been merged.

**Comment by TheMetalHead** [comment]
Also changed playerlib.min.js
Confirmed the fix is good on v6.7.0 ok.
Thank you @bitkeeper and @moodeaudio.

**Comment by moodeaudio** [comment]
Oops, I just pushed the min

Thx for confirming the fix :-)
