### ISSUE TITLE
Use of pi3-disable-wifi and pi3-disable-bt is obsolete

### ISSUE THREAD

**Issue by bitkeeper** [moode-player/moode#151]
Issue:
The pi3 specific overlays `pi3-disable-wifi` and `pi3-disable-bt` are replaced by `disable-wifi` and `disable-bt`.
Currently the obsolute names are kept as backwards alias.

Reproduce:
* disable wifi and bt on a pi3 form the system configuration page
* reboot
* run `sudo vcdbg log msg` and analyse the output:
```bash
...
002446.804: dtwarn: overlay 'pi3-disable-wifi' has been renamed 'disable-wifi'
002447.391: brfs: File read: 1430 bytes
002452.286: brfs: File read: /mfs/sd/overlays/disable-wifi.dtbo
002480.871: Loaded overlay 'pi3-disable-wifi'
002522.509: dtwarn: overlay 'pi3-disable-bt' has been renamed 'disable-bt'
002523.094: brfs: File read: 387 bytes
002525.456: brfs: File read: /mfs/sd/overlays/disable-bt.dtbo
002560.710: Loaded overlay 'pi3-disable-bt'
...
```
More information can be found in /boot/overlays/README

**Comment by moodeaudio** [comment]
PR to address this has been merged.
