### ISSUE TITLE
either build_recipe_v2.25.txt or moode-r671.zip missing something

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#155]
**Problem:**

build_recipe_v2.25.txt, line 503:
```
sudo cp ./moode/var/local/www/db/moode-sqlite3.db.default /var/local/www/db/moode-sqlite3.db
```

The default database file doesn't exist in moode-r671.zip (or, as far as I can tell, in any version of the zip file after r652)

**Solution:**

Either
1) build the database and add it to the moode-r671.zip file

or

2) add a step to build_recipe_v2.25.txt something like
```
sudo sqlite3 /var/local/www/db/moode-sqlite3.db < ./moode/var/local/www/db/mppde-sqlite3.db.sqlite
```

**Personal preference:** solution 2.

**Comment by moodeaudio** [comment]
Good catch. I just pushed a commit that should fix this.
