### ISSUE TITLE
build_recipe_v2.2.6.txt - unnecessary usage of sudo

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#163]
A recurring pattern in the recipe goes something like this for a single component
```
sudo cp ./moode/other/.../something ./
sudo unzip something or (sudo tar xfz something)
cd something-dir
sudo <configuration steps>
sudo make
sudo make install
cd ~
sudo rm ...
```
However, in (nearly?) all cases only the `make install` step actually requires elevated privilege.

Without debating any questions of best practices or of least privilege, a practical consequence  is the need to be consistent in the use of `sudo` or the component-build fails.

The following few issues identify inconsistencies in the recipes for building several of the additional components.

**Comment by moodeaudio** [comment]
There's a couple occurrences of make w/o sudo so prolly best to just add sudo to those rather than remove sudo from all the other make commands, especially given the automated builder runs as root.

Examine the commit and let me know what you think.
