### ISSUE TITLE
build_recipe_v2.2.6.txt - COMPONENT 5 - Squeezelite typos

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#164]
// COMPONENT 5 - Squeezelite

Lines 879-881 read
```
export CFLAGS="-O3 -march=native -mcpu=native -DDSD -DRESAMPLE -DGPIO -fno-fast-math -mfloat-abi=hard -pipe -fPIC"
cat ./scripts/squeezelite-ralphy-dsd.patch | patch -p 0
make
```

Since lines 880-881 are executed in a subdirectory owned by root with permissions `drwxr-xr-x`, they need appropriately placed `sudo` commands

```
cat ./scripts/squeezelite-ralphy-dsd.patch | sudo patch -p 0
sudo make
```

Also, to avoid side effects in following sections, the CFLAGS environment variable should be cleared when finished.
```
unset CFLAGS
```

(note: I haven't checked this component recipe in 32-bit RaspiOS yet but in my 64-bit build, the compiler coughs up a hairball on the CFLAGS settings.)

**Comment by moodeaudio** [comment]
Fixed
