### ISSUE TITLE
Spotify casting is currently broken

### ISSUE THREAD

**Issue by ahydronous** [moode-player/moode#170]
Whenever I try to connect to Moode from my iPhone it connects for a half a second (but I cannot initiate play) and then the iPhone-Moode connection is immediately dropped.  
If I go to moode.local it also does show ‘Spotify active’ for a split second.  
A reboot does not fix the issue. Airplay works fine.

**Comment by moodeaudio** [comment]
Works OK on my end. I'm testing with the Spotify app (Premium account) on my iPhone.

I'd need to be able to repro your issue in order to troubleshoot.
