### ISSUE TITLE
Files missing via upnp

### ISSUE THREAD

**Issue by gvijayakumar-16** [moode-player/moode#171]
Moode version: 6.7.1

I am using my music source via upnp and when I update the library many songs were missing. Upon checking the logs, I found the below. 

Logs are not super helpful. But the files with Unknow.flac are the one's missing from my library. Any ideas why this is happening? 

`
Aug 06 10:15 : update: added HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: added HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Aaruyire (From _Guru_).flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
Aug 06 10:15 : update: updating HDD/Browse Folders/Mine/Songs/Tamil Collections/Timeless at 50 - A.R. Rahman/Unknown.flac
`

**Comment by moodeaudio** [comment]
Your best bet is to post in the support section of the moOde Forum. There are a couple users that have some experience in UPnP and might be able to help.
