### ISSUE TITLE
DACBerry ONE+ profile

### ISSUE THREAD

**Issue by TiemenSch** [moode-player/moode#172]
The DACBerry One+ is a nice Raspberry Pi hat that features both Optical in and analog out. It would be awesome to pipe its digital input straight to its analog out!

With the current recommended "Hifiberry DAC plus" profile you only get analog audio output out of the box.

I think the required steps should be either in the shell script or asound.conf over at https://www.osaelectronics.com/learn/tutorials/dacberry-one-quick-start-guide/#retropie

**Comment by moodeaudio** [comment]
I would need a sample device, a technical description of its options that are exposed via ALSA including their ranges, units etc, how to accomplish routing input to output and access to a tech contact to answer questions.
