### ISSUE TITLE
/var/www/command/listall.sh should use case-independent regex

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#175]
As determined in a recent Forum thread, the thmcache scheme fails when lower-case track file extensions aren't used.

The culprit is the use of '-regex' expressions in the find commands in /var/www/command/listall.sh

These should be '-iregex' in each find, e.g.,

```
find /mnt/NAS -depth -mindepth 1 -type f -regex ".*\.${TYPES_REGEX}" -printf "file: "NAS/"%P\n"
```
should be
```
find /mnt/NAS -depth -mindepth 1 -type f -iregex ".*\.${TYPES_REGEX}" -printf "file: "NAS/"%P\n"
```

**Comment by moodeaudio** [comment]
Good catch. No need for a PR. I'll fix on. my end and push the commit :-)
