### ISSUE TITLE
spotify or tunein support?

### ISSUE THREAD

**Issue by Wqrld** [moode-player/moode#22]
I just installed a new machine on the newest version of moode but im not getting any audio output using the inbuilt soundcard, what would i need to turn on?

**Comment by moodeaudio** [comment]
post the output from moode log and i'll have a look

cat /var/log/moode.log

**Comment by Wqrld** [comment]
https://paste.imluc.ga/puvaxewegi.sql @moodeaudio

**Comment by Wqrld** [comment]
seems like the alsa speaker-test is also not working

**Comment by Wqrld** [comment]
fixed by downsampling the alsa audio to mono and rebooting

**Comment by moodeaudio** [comment]
The log output shows 

ALSA mixer name (Mic)

The mixer name for the on-board audio device is 'PCM'.

This suggests something external to moOde software.

**Comment by Wqrld** [comment]
Coming from mopidy, i really liked the tunein and spotify support on the web ui, does moode also have a  integration for one of those? (i know you offer spotify connect but that would be a cool extra)

**Comment by moodeaudio** [comment]
Our approach is to implement the audio renderers and make use of their streaming protocols to play from the native Music Service applications. It's been my experience that the native apps are always much better than integration attempts.

Are u using the new moOde 5 beta?

**Comment by Wqrld** [comment]
> Our approach is to implement the audio renderers and make use of their streaming protocols to play from the native Music Service applications. It's been my experience that the native apps are always much better than integration attempts.
> 
> Are u using the new moOde 5 beta?

no i'm using the public moode 4, is 5 already public / feature list? 
I'm likely going to try to run mopidy alongisde of moode for the best experience

**Comment by Wqrld** [comment]
I'm also only able to skip songs and not use new ones from other playlists, if this requires spotify premium where is the config file?

**Comment by Wqrld** [comment]
i just installed mopidy next to this for the best experience, keeping this open as a suggestion

**Comment by moodeaudio** [comment]
moOde 5 beta
http://moodeaudio.org/forum/showthread.php?tid=1183

Spotify track/skip issue is fixed in this beta.
