### ISSUE TITLE
remove all reference to google play music

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#229]
Google Play Music is finally, officially [dead](https://play.google.com/music/managemusic?u=0#).

Time to remove all reference to it in the moOde code base, including in the following modules
```
etc/upmpdcli.conf
etc/upmpdcli.conf.default
other/build/build_recipe_v2.xx.txt and its new 64-bit build cousin
user/local/bin/moodeutl
www/inc/playerlib.php
www/templates/upp-config.html
www/upp-conf.php
www/js/playerlib.js
```
and any I overlooked such as the minified js files.

Finally, update
```
www/relnotes.txt
```

**Comment by moodeaudio** [comment]
I'll do the pruning.

**Comment by moodeaudio** [comment]
Done :-)
