### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by ShalokShalom** [moode-player/moode#25]
Including screenshots on your homepage might be a good idea to avoid forcing users to install the application just in order to take a brief look onto the UI. 

Or let them google for (old and outdated) screenshots somewhere on the Internet.

**Comment by moodeaudio** [comment]
No disagreement on my part that high quality documentation and product pictures are a valuable asset to any project.

Maybe you would be willing to help our project and take on this task ??

-Tim

**Comment by Norde** [comment]
I'll do some screenshot (with description) of incoming 5.0 release :)

I think using a slideshow in place of actual moode 4.4 background could be fine. (http://moodeaudio.org/img/moode-r44.png)

**Comment by moodeaudio** [comment]
I added a Lightbox w/screen shots to the Features section.

**Comment by Norde** [comment]
Sorry for not being helpful 😞

**Comment by ShalokShalom** [comment]
All fine. I like it that way. :)
