### ISSUE TITLE
AlbumCover Context Menu Close

### ISSUE THREAD

**Issue by chris-rudmin** [moode-player/moode#26]
Close button does not do anything, even if the album tracks are open.
- Moode v5.0.
- Browser: Chrome v73

<img width="1023" alt="Screen Shot 2019-04-15 at 10 21 49 AM" src="https://user-images.githubusercontent.com/506755/56140255-8b4fa180-5f68-11e9-815c-32b0cd557c0c.png">

**Comment by moodeaudio** [comment]
Close = close the context menu. The Track list item toggles the track list open/closed.

**Comment by chris-rudmin** [comment]
I see. Thank you for clarifying. :+1:  v5 looks nice.

**Comment by moodeaudio** [comment]
Thanks :-)

As soon as the post-release dust settles we'll take a look at the Library enhancements.
