### ISSUE TITLE
Special Characters in SSID

### ISSUE THREAD

**Issue by soviet-kitsch** [moode-player/moode#272]
Moode audio does not recognise special characters when entering SSID.

My SSID is (was) "( ͡° ͜ʖ ͡°)", which Moode marked as invalid but which is a fully functional SSID.

**Comment by moodeaudio** [comment]
This has been fixed for upcoming 7.0.1 bug fix release.

**Comment by Smo-ky** [comment]
> This has been fixed for upcoming 7.0.1 bug fix release.

I m on 7.0.1, my SSID contains spl character **Smö** but still 7.0.1 moode shows **Sm**& few irrational  alphabets instead of **ö**

**Comment by moodeaudio** [comment]
I'll reopen. Maybe a dev will figure out what is going on.
