### ISSUE TITLE
UPNP

### ISSUE THREAD

**Issue by gerben-b** [moode-player/moode#277]
I have Moode running with only radio's on a Raspberri Pi 3, I also have a Ubuntu based UPNP server. How can i access that from Moode? I already enabled the UPNP browser in de Moode settings but that does not seem to do anything.

**Comment by moodeaudio** [comment]
Try posting your question in the support section of the Moode Forum. http://moodeaudio.org/forum

**Comment by gerben-b** [comment]
That won't help. It is a bug.

**Comment by moodeaudio** [comment]
What is the bug?

**Comment by gerben-b** [comment]
I followed all possible suggestions to add my upnp source to Moode bun none worked. I enabled the upnp browser and then tried to add a upnp source to the library. When i schoose scan, it reports nothin while all other upnp clients perfectly detect my upnp (rygel) server.

**Comment by moodeaudio** [comment]
This is a question better addressed in the Forum. There are users with UPnP experience that might be able to help troubleshoot.

**Comment by gerben-b** [comment]
Too bad, that won't work. I'll try something else then.
