### ISSUE TITLE
dtparm=audio=off in file 'config.txt'

### ISSUE THREAD

**Issue by JuramemO** [moode-player/moode#293]
Dear all!

To get my system to have a sound output, I manually had commend out the parameter

> dtparam=audio=off
to
> #dtparam=audio=off

Beside this, everything was working out of the box!

Great project!!
Best Regards, 
Marcus

Board:         Raspberry Pi3+
Soundcard: HiFi-Berry Amp2
OS:              moOde audio player 7.0.1, installed as iso

**Comment by moodeaudio** [comment]
I ran a quick test with a Hifiberry dac+ and the config below with dtparam=audio=off works fine. The Amp2 uses same dacplus overlay so I'm not sure why in your case the dtparam has to be commented out. You might want to post in the support section of the Moode Forum to see of other users have same issue.

```
pi@rp2:~ $ cat /boot/config.txt
disable_splash=1
disable_overscan=1
hdmi_drive=2
hdmi_blanking=1
hdmi_force_edid_audio=1
hdmi_force_hotplug=1
hdmi_group=0
dtparam=i2c_arm=on
dtparam=i2s=on
dtparam=audio=off
dtoverlay=hifiberry-dacplus
#dtoverlay=disable-wifi
#dtoverlay=disable-bt
```
