### ISSUE TITLE
Any possible release on Rock64 Pi or TV box by Amlogic S9xxx S8xxx 

### ISSUE THREAD

**Issue by godt2p4** [moode-player/moode#30]
MoOde is more wonderful than Volumio. Unfortunately, only Raspberry Pi version is available for MoOde. On the other hand, Volumio can support Rock64,  TV box by Amlogic S9xxx S8xxx , and other Pi version.
I'm wondering if there is someone who has accomplished the installation of MoOde for Rock64 or S9XXX S8XXX Pi.
Looking forward to your kindly response.
Thank you!

**Comment by moodeaudio** [comment]
Some info at these links. 
https://github.com/moode-player/moode/pull/6
https://github.com/jesset/RPi-audio-kernel-build

It looks like u have to make your own arm64 kernel.
