### ISSUE TITLE
Missing autocfg options

### ISSUE THREAD

**Issue by bitkeeper** [moode-player/moode#301]
This issue is created to provide an overview of the settings still to implement for autoCfg:

System Config Page:
* System modifications
  * Kernel architecture 
  * USB auto-mounter
  * ~USB UAC2 fix~ (NA)
* Local Display:
  * Mouse cursor
  * Screen blank
  * Wake dispay on play
  * Brightness
  * Pixel Ratio
  * Rotate screen
* Local Service:
  * Metadata file
  * LCD update engine
  * GPIO butto handler
     * + configuration
  * SHH term server
* ~Maintenance:~
  * ~Debug logging~ Think this one shouldn't be part of the backup 

~LibraryConfig Page:~
* ~Music Database:~ 
  * ~Update MPD database on USB insert or remove~_(done)_
  
Audio Config Page:
* I2S Audio Device
  * Driver Options
* Alsa Options:
  * Max Alsa Volume
  * ~Alsa Output mode~ _(7.3)_
  * ~Alsa loopback~ _(7.3)_
* MPD Options:
  * ~General:~
    * ~MPD version~ Think this one shouldn't be part of the backup
    * ~Autoplay after start~ _(done)_
  * ~Auto-shuffle:~ _(done)_
    * ~Auto-shuffle~ _(done)_
    * ~Mode~ _(done)_
    * ~Tag filter~ _(done)_
  * Volume options:
    * ~Volume step limit~ _(done)_
    * ~Max MPD volume~ _(done)_
    * ~Display dB volume~ _(done)_
    * USB volume knob
   * Rotary encoder
  * ~DSP options:~
    * ~Crossfade~ _(done)_
  * HTTP streaming:
    * Streaming server
	* Port
	* Encoder
  * Equalizers:
        * ~CamillaDSP~ _(done)_
	* Graphic EQ config from edit button)
	* ~CamilladDSP config from edit button~ _(done)_
  * Audio Renders:
	* Bluetooth:
	  * ~Speaker sharing~ _(7.2)_
	  * BlueZ config (By edit button)
  * Airplay renderer:
      * Airplay config (By edit button)
  * ~Spotify renderer:~
      * ~config (By edit button)~ _(7.2)_
  * Squeezelite renderer:
      * config (By edit button)
~UPnP/DLNA~:
  * ~UPnP config (By edit button)~ _(7.2)_

~Graphic EQ Curves Page:~
  * ~Curves _(WIP)_~ _(7.5)_
	
~CamillaDSP settings Page~:
  * ~Default device~ _(7.1)_

Clock Radio Settings Page:
  * _everything_
  
Input Source Page:
  * _everything_
  
Radio Manager Page:
  * Sort tag
  * Group method
  * Show/Hide:
    * moOde stations
	* other stations

**Comment by moodeaudio** [comment]
Ugh, lotta work.

**Comment by bitkeeper** [comment]
Yep, but for now I think it missing to much to call it a backup and restore solution.
I don't expect that everything will be implemented in one or two minor version.

For now I'm implementing the items marked with WIP.
I don't use any other renderer, so it would be nice if someone else could pickup those ;-)

**Comment by moodeaudio** [comment]
Agree. I'll do the renderers.

**Comment by bitkeeper** [comment]
First batch is ready in PR #307.

**Comment by bitkeeper** [comment]
Also missing are the new settings from 7.3among which:
- alsa output mode
- alsa loopback

**Comment by moodeaudio** [comment]
Issue has become stale but for sure updating autoconfig and backup/restore is important. How can it be prioritized is the question...

**Comment by moodeaudio** [comment]
All settings in upcoming moode 9 should be reflected in autocfg. If any are missing users can report in the Forum and they will go on the TODO list.
