### ISSUE TITLE
Use JFD's albumart.py script in place of upexplorer

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#309]
### Problem

The moOde module `playerlib.php` uses Jean-Francois Dockes' `upexplorer` utility with its `--album-art` option to query the albumArtURI for the currently playing track on a UPnP/AV renderer. This does not work properly with an OpenHome renderer. See for example my forum posts beginning at http://moodeaudio.org/forum/showthread.php?tid=3278&pid=29171#pid29171

### Approach

JFD emailed to me and Tim a Python3 script `albumart.py` which deals solely with the albumArtURI from either a UPnP/AV renderer or an OpenHome renderer. I put this script in my own [albumart repo](https://github.com/TheOldPresbyope/AlbumArt) in order to capture my observations and changes I made to get it working with moOde.

### Current status

At the time of this writing, there's a bug relating to error messages leaking into the output which needs to be resolved.

**Comment by moodeaudio** [comment]
I updated the script (renamed to upnp_albumart.py) to use sys.exit instead of OS._exit and tests were successful using miniDLNA and Linn Kazoo Ctl point. Commits have been pushed so go ahead and close when convenient.
