### ISSUE TITLE
Spotify Connect in 5.3.1

### ISSUE THREAD

**Issue by godt2p4** [moode-player/moode#37]
Great upgrade in 5.3.1 and Spotify Connect is finally workable. But it is quite strange that the stream can only work for a short time, like 3-5 mins, and the Spotify Connect will be enclosed, together with the pause of on-going music in Spotify software (android app and windows software meet the same situation).
Please help to fix it, thanks a lot!

**Comment by moodeaudio** [comment]
Post your issue in the moOde Forum support section.
http://moodeaudio.org/forum
