### ISSUE TITLE
After installing version 7.1.0 can't install BubbleUPnP Server

### ISSUE THREAD

**Issue by DAlam6er** [moode-player/moode#374]
I install BubbleUPnP Server according to the instruction

_wget https://launchpad.net/~bubbleguuum/+archive/bubbleupnpserver/+files/bubbleupnpserver_0.9-5_all.deb_
_sudo dpkg -i bubbleupnpserver_0.9-5_all.deb_
![BubbleUPnP error](https://user-images.githubusercontent.com/12190799/111763665-73e76480-88b3-11eb-877c-c2412b686978.png)

**Comment by moodeaudio** [comment]
Try posting in the Support section of the Moode Forum. There is a thread titled "Official moOde 7.1.0 support thread"
http://moodeaudio.org/forum
