### ISSUE TITLE
Suggestion: display the Spotify / Airplay / Squeeze logo on the 'x Active' overlay screen

### ISSUE THREAD

**Issue by ahydronous** [moode-player/moode#380]
Basically the title. I feel that it would add a little flourish to the otherwise spartan overlay. A good spot for it might be above the 'x Active' text.

**Comment by moodeaudio** [comment]
I don't know about the Squeezelite logo but I think Airplay and Spotify logo's are licensed and so legally they can't be used without permission from the copyright/trademark holder.
