### ISSUE TITLE
Bug: buzz on boot up with software volume control and USB

### ISSUE THREAD

**Issue by sunbubble** [moode-player/moode#395]
## Bug report
I get a loud buzz on boot up if I have software volume control enabled until I select some audio to play.
It doesn't happen if I have the HW volume control option enabled.

Let me know if you need more data to diagnose this issue.

## Reproduction scenario
1. Have software volume control enabled
2. boot or reboot
3. I hear a loud "sawtooth wave like" buzz **until** I select any active audio source. Tried with internet radio and Spotify connect. 

## Setup:
- Moode 7.1.0
- Raspberry pi 4 (no hats)
- USB out connected to DAC [Topping D30Pro]. The UAC2 option is enabled but issue reproduces without as well. Also reproduces both on the USB2 and USB3 ports.

**Comment by moodeaudio** [comment]
I'm not able to repro with Pi4 and my USB DAC but you can always try posting in the Moode Forum to see if someone else might be able to repro your issue.
