### ISSUE TITLE
 thumbnails affect genre/artist aggregation

### ISSUE THREAD

**Issue by brainchild0** [moode-player/moode#402]
If albums occur in the library for the same artist or genre, and some but not all have album thumbnails, then the three-column library view shows genre or artist items twice, once each for the group with versus without thumbnails. 

Availability of a thumbnail should not affect aggregation.

**Comment by moodeaudio** [comment]
You will need to post these kinds of questions in the support section of our Forum.
http://moodeaudio.org/forum
