### ISSUE TITLE
Simplify donations by adding funding through Github

### ISSUE THREAD

**Issue by gruentee** [moode-player/moode#415]
Hi, 

first of all – thanks for making moode. 

Second – when trying to donate I noticed there is no sponsorship button to be found at the Github page. Is there any reason against it? If not I'd suggest adding it in order to make it easier for people to support the project via donations.

Best
Constantin

**Comment by moodeaudio** [comment]
Hi,

I didn't know that was available. I'll check it out, thanks :-)

**Comment by moodeaudio** [comment]
After reviewing it, the GitHub sponsorship system seems a bit too involved for our project at this time. I did add a simple PayPal button to the repo though which I think will make it easier for people to donate.

**Comment by gruentee** [comment]
Okay, seems reasonable.
