### ISSUE TITLE
moode REL. 7.3.0 install problems

### ISSUE THREAD

**Issue by enzolarizza** [moode-player/moode#416]
I want to install version 7.3.0 from zero,
I downloaded the iso of moode 7.3.0 and then I created the SD.
On my RPi4 - 4Gb  the wi-fi AP does not activate, after several minutes from turning on the RPi4, **the pc does not see any moode wi-fi network.**
I downloaded the .iso file several times and created several SDs but it **doesn't work**.
I state that everything with the Moode 7.2.1 and 7.1.0 versions everything works regularly.
Thanks and best regards

**Comment by moodeaudio** [comment]
For troubleshooting these types of issues please post in the Support section of the Moode Forum. I only use repo issues for PR's and other matters regarding the sources.
