### ISSUE TITLE
Add powersave cpu governor in the web ui config.

### ISSUE THREAD

**Issue by tibrezus** [moode-player/moode#449]
I have my moode installed on a rpi3 which is connected to a 5V/0.5A power source. I use it because is a very low noise power source and is also very convenient. It works fine 99% of the time while listening high-res files, but when I try to update volumio and the CPU usage goes high files on the SD-card get corrupted because of insufficient power.
Limiting the multiplier to it's minimum solves this issue for me, but is very annoying to configure it manually and setup a crontab to overwrite the moode configuration. So I added the powersave config on the System Config to have a fast solution to whoever incurs in SD card data corruption due to the low current power source.
It also heats less and 600Mhz is more than enough to handle all the workloads in moode.
I have started doing the changes here: https://github.com/moode-player/moode/pull/448
Please take a look.
Cheers

**Comment by moodeaudio** [comment]
https://github.com/moode-player/moode/pull/448
