### ISSUE TITLE
Feature Request: Allow MPD Satelite DB

### ISSUE THREAD

**Issue by roizcorp** [moode-player/moode#457]
MPD has a neat feature where it is DB is maintained in a single server while all other MPD servers in the network use it (rather than update each one of them)

This means that the `db_file "/var/lib/mpd/database"` is disabled

`database {
        plugin "proxy"
        host "some.ip"
        port "6600"
}
`

**Comment by moodeaudio** [comment]
We take feature requests in our Forum https://moodeaudio.org/forum

Search for user "cprogrammer" who posted a similar request a while back. If there is enough demand for something like this it can be added to the TODO list.
