### ISSUE TITLE
Cover image not showed when % in radio station name

### ISSUE THREAD

**Issue by xciser77** [moode-player/moode#460]
We have a radio station named 100% NL, but when I try to add a cover image to it, it is not showed.
I tried everything until I named added the station as NL 100 without the % and than the image is shown

I am running version 7.5 on a rpi 4

**Comment by moodeaudio** [comment]
Support for non-developer issues is handled over at our Forum. Feel free to post a thread in the Support sub-forum at https://moodeaudio.org/forum
