### ISSUE TITLE
build_recipe.txt typos

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#461]
other/build/build_recipe.txt V2.34, last commit 844099f

Lines 94, 95, 6, 97, 122, 123 reference moode-r741.zip; should now be moode-r750.zip

In line 173

`sudo cp ./moode/other/alsacap/alssacap /usr/local/bin`

alssacap should be alsacap

**Comment by moodeaudio** [comment]
Fixed :-)
