### ISSUE TITLE
another build_recipe.txt typo

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#462]
Rats; had this in my notes and overlooked it.

Version 2.34 Line 401

`sudo wget http://www.musicpd.org/download/mpd/0.22/mpd-0.23.3.tar.xz`

should be .../mpd/0.23/...

**Comment by TheOldPresbyope** [comment]
Ah, and the 7.5.0 relnotes say

"- UPD: Bump to Meson 0.59.2"

but lines 162-167 in build_recipe.txt still reference meson 0.55

**Comment by moodeaudio** [comment]
Fixed and fixed :-)
