### ISSUE TITLE
Forum: IP banned

### ISSUE THREAD

**Issue by csejourne** [moode-player/moode#468]
Hello,

I know this is not the place, but I tried to contact people from the Moode audio forum but to no avail. That's why I try here.

I got IP banned from the Moode audio forum for "spam" after posting a new thread to get some help. I am pretty sure my post was not spam, and I guess I got banned for being detected as a bot (my nickname is quite strange). Where can I discuss this matter? I contacted the forum support through 2 different mails but I did not get any response.

Thanks, and thanks for the awesome software (though I can't read documentation anymore)

**Comment by moodeaudio** [comment]
Email tim at moodeaudio dot org and include the following so I can investigate.

Date the thread was posted
Userid
Email address
IP address
