### ISSUE TITLE
log_network_info($interface) function assumes too much

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#474]
## Problem
In /var/www/command/worker.php: `log_network_info($interface)` 

The following code assumes that /etc/resolv.conf contains lines in the specific order: comment line, domain line, nameserver line
```
        $line3 = sysCmd("cat /etc/resolv.conf | awk 'NR==3 {print $2}'")[0]; // nameserver
        $line2 = sysCmd("cat /etc/resolv.conf | awk 'NR==2 {print $2}'")[0]; // domain
        $primary_dns = !empty($line3) ? $line3 : $line2;
        $domain_name = !empty($line3) ? $line2 : 'None';
        workerLog('worker: Pri DNS (' . $primary_dns . ')');
        workerLog('worker: Domain  (' . $domain_name . ')');
```

However, this is not always true. For example, when I configure my moOde player on my LAN with static IP with primary nameserver 8.8.8.8 and secondary nameserver 1.1.1.1, I get a resolv.conf which begins

```
# Generated by resolvconf
nameserver 8.8.8.8
nameserver 1.1.1.1
...more nameserver lines with IPv6 addresses
```
for which the moOde log reports
```
worker: Pri DNS (1.1.1.1)
worker: Domain  (8.8.8.8)
```
instead of the expected

```
worker: Pri DNS (8.8.8.8)
worker: Domain (None)
```
As well, that conditional in the `$domain_name =` line looks bogus (but maybe it's just me)

## Suggested fix
1. Replace the existing resolver extraction code with
```
$line3 = sysCmd("cat /etc/resolv.conf | awk '/^nameserver/ {print $2; exit}'")[0]; \\first nameserver entry of possibly many
$line2 = sysCmd("cat /etc/resolv.conf | awk '/^domain/ {print $2; exit}'")[0]; \\first domain entry of possibly many
```
This construction avoids matching comment lines containing the same strings

2. check the logic of the `$domain_name =` line
## Note
per `man resolv.conf` there can be more than one `domain` line, in which case the last one wins. I've never seen more than one but my suggested fix chooses the first. As well, in general there can be a `search` line instead of a `domain` line. Both these cases seem unlikely in moOde given the way we construct `resolv.conf`.

**Comment by moodeaudio** [comment]
Fixed in this commit
https://github.com/moode-player/moode/commit/f20bfe36da8c3f3403b85477b27abdfa577956fb
