### ISSUE TITLE
USB Thumb Drive Scanned but not in Library

### ISSUE THREAD

**Issue by tokenwizard** [moode-player/moode#475]
I'm running a fresh install of MoOde on a rPi4 via the provided img file. I can successfully play the included SOMA FM Streaming Sources.

I plugged in a USB Thumb Drive with 156GB of music that I was using with a Mopidy setup before. It is formatted EXT4 and after Updating the Library, it looks like it detected the Music and parsed it:

![image](https://user-images.githubusercontent.com/24832561/147962898-c27d1ea2-080c-4766-a1c3-00a7ed84214a.png)

But when I go back to the main page, even after a Restart of the System, none of the local music files are showing. I'm still only seeing the included Streaming Sources and the one Audio Test file on the SDCard. 

What am I missing. Is there something else that needs to be done to populate USB music files onto the main screen? I also don't see any other way to "Browse" the Music Library. Since I have all my music on this Thumb Drive, I prefer not to use NFS/SMB. I didn't see anything else on the Setup Guide of in the Forums that seems to be relevant to my issues. 

Looking in the Web-based SSH terminal, when I run 'mount' I see the USB Drive did auto-mount with the following parameters:
![image](https://user-images.githubusercontent.com/24832561/147963400-aa393f56-9f71-43ea-b164-0beea754f896.png)

And here is a snapshot of the permissions:
![image](https://user-images.githubusercontent.com/24832561/147963556-5e311c80-e022-4eec-a1ed-04a3f83e339e.png)

![image](https://user-images.githubusercontent.com/24832561/147963611-a9e58ea1-223b-490a-96a0-d3e937f52e8f.png)
(Note, after having no success, I tried chown-ing the T and J's Radio folder from the default of shellinabox:audio to pi:audio since it seems the services are running as either the 'pi' user or the 'mpd' user. Also, both 'pi' and 'mpd' users are in the 'audio' group. 

Thanks in advance for any guidance!

________________System Info Pasted Below_____________

		
S Y S T E M   P A R A M E T E R S

moOde release		= 7.6.1 2021-12-17
RaspiOS			= 10.6
Linux kernel		= 5.4.77-v8+ #1371
Platform		= Pi-3B 1.2 1GB
Architecture		= aarch64 (64-bit)
System uptime		= up 8 minutes
Timezone		= America/New_York
Current time		= 2022-01-03 12:49:06

Host name		= TandJ-Radio
Ethernet address	= 192.168.7.157
Ethernet MAC		= b8:27:eb:a1:56:5f
WLAN address		= unassigned
WLAN MAC		= no adapter
WLAN country		= US

SoC identifier		= bcm2837 
Core count		= 4
Kernel timer freq	= 250 Hz
SDCard freq		= 25 MHz
USB boot		= not enabled
Warranty		= OK

Root size		= 15G
Root used		= 20%
Root available		= 12G
Root expand		= expanded
Memory total		= 934 MB
Memory free		= 767 MB
Memory used		= 167 MB
SoC temperature		= 39.7°C
Throttled bitmask	= 0x0
Throttled text		= No throttling has occurred

CPU governor		= ondemand
Onboard WiFi		= Off
Onboard BT		= Off
HDMI output		= Off
LED state		= 1,1
IP addr timeout		= 90 (secs)
Ethernet check		= No
USB auto-mounter	= udisks-glue
SSH term server		= On

PHP-FPM version		= 7.3.19
NGINX version		= 1.14.2
SQLite3 version		= 3.27.2
Hostapd version		= 2.8-devel
WiringPi version	= 2.50
RPi.GPIO version	= 0.7.0

A U D I O   P A R A M E T E R S

Audio device		= Pi Headphone jack
Interface		= SOC
Mixer name		= Headphone
Hardware mixer		= Yes
Supported formats	= U8, S16_LE
ALSA max volume		= 100
ALSA output mode	= Default (plughw)
ALSA loopback		= Off
MPD max volume		= 100
Volume step limit	= 10
Display dB volume	= Off
Audio source		= Local
Output device		= Local
Resume MPD		= No
Volume knob		= 0
Volume mute		= Unmuted
Saved MPD vol		= 0
Preamp volume		= 0
ALSA version		= 1.1.8-1+rpt1
SoX version		= 0.1.2-3

Bluetooth controller	= Off
Pairing agent		= Off
Airplay receiver	= Off
Spotify receiver	= Off
Squeezelite		= Off
RoonBridge		= Not installed
UPnP client		= On
DLNA server		= Off
GPIO button handler	= Off
Multiroom sender	= Off
Multiroom receiver	= Disabled
UPnP browser		= Off

Auto-shuffle		= On
Ashuffle mode		= Track
Ashuffle filter		= None
Autoplay		= Off
Rotary encoder		= Off
Encoder params		= 100 2 3 23 24
USB volume knob		= Off
Polarity inversion	= Off
Crossfeed		= Off
Crossfade		= Off
Parametric EQ		= Off
Graphic EQ		= Off
CamillaDSP		= off
MPD httpd		= On
Ignore CUE files	= Yes

P R E F E R E N C E S

Appearance
----------------------
Theme			= Green Tea
Accent color		= Grass
Alpha blend		= 1.0
Adaptive background	= No
Background image	= No
Cover backdrop		= No
Cover blur		= 20px
Cover scale		= 1.25
Renderer backdrop	= No
Font size		= Normal

Playback
----------------------
Show Queue thumbs	= Yes
Show Now-playing icon	= Yes
Show CoverView playbar	= Yes
Show extra metadata	= album,genre,track,disc,date,composer,conductor,performer,encoded
Search site		= DuckDuckGo
Playback history log	= No

Library
----------------------
One touch album		= Show tracks
One touch radio		= Play next
Albumview sort order	= by Artist
Tagview sort order	= by Artist
Recently added		= 1 Month
Show sample rate	= No
Cover search pri	= Embedded cover
Pixel ratio		= 1
Thumbnail resolution	= Auto
Thumbnail columns	= 6/2 (Default)

Library (Advanced)
----------------------
Tag view genre		= Genres
Tag view artist		= Artist
Album key		= Album@Artist (Default)
Include comment tag	= No
Library filter		= full_lib
Library filter str	= 
Ignore articles		= a,an,the
Show tagview genres	= Yes
Show tagview covers	= Yes
Ellipsis limited text	= No
UTF8 character filter	= No

CoverView
----------------------
Automatic display	= Never
Backdrop style		= Gradient (Linear)

R A D I O   M A N A G E R   S E T T I N G S

Sort tag		= Name
Group method		= No grouping
Show moOde stations	= No action
Show other stations	= No action

M P D   S E T T I N G S

Version			= 0.23.4_p0x3
Volume type		= software
ALSA device		= hw:1
SoX resampling		= disabled
Selective resampling	= disabled
SoX quality		= high
SoX multithreading	= off
DSD over PCM (DoP)	= no
Replaygain		= off
Replaygain preamp	= 0
Volume normalization	= No
Audio buffer		= 16 (MB)
Output buffer size	= 128 (MB)
Max playlist items	= 20000
Input cache		= 128 MB

B L U E T O O T H   S E T T I N G S

Bluetooth ver		= 5.50
Bluealsa ver		= v3.0.0
Speaker sharing		= No
Resume MPD		= No
PCM buffer time		= 500000 (µs)

A I R P L A Y   S E T T I N G S

Version			= 3.3.8
Friendly name		= Moode Airplay
ALSA device		= hw:1
Interpolation		= soxr
Output bit depth	= S16
Output sample rate	= 44100
Session interruption	= no
Session timeout		= 120 (ms)
Latency offset		= 0.0 (secs)
Audio buffer		= 0.2 (secs)
Resume MPD		= No

S P O T I F Y   S E T T I N G S

Friendly name		= Moode Spotify
ALSA device		= plughw:1
Bit rate		= 160
Initial volume		= 0
Volume curve		= log
Volume normalization	= No
Normalization pregain	= 0
Autoplay		= No
Resume MPD		= No

S Q U E E Z E L I T E   S E T T I N G S

Version			= 1.9.7-1270 "DSD/SRC enabled"
Friendly name		= Moode
ALSA device		= hw:0
ALSA params		= 80:4::1
Output buffers		= 40000:100000
Task priority		= 45
Codec list		= flac,pcm,mp3,ogg,aac,alac,dsd
Other options		= -W -D 500 -R E -S /var/local
Resume MPD		= No

L O C A L   D I S P L A Y   S E T T I N G S

Local UI display	= Off
Mouse cursor		= On
Screen blank		= 600 Secs
Wake display on play	= Off
Brightness		= 255
Pixel aspect ratio	= Default
Rotate screen		= 0 Deg

M O O D E   S T A R T U P   L O G

20220103 124044 worker: -- Start
20220103 124044 worker: Successfully daemonized
20220103 124045 worker: Integrity check (passed)
20220103 124045 worker: File check (OK)
20220103 124046 worker: Session vacuumed
20220103 124046 worker: Session loaded
20220103 124046 worker: Debug logging (OFF)
20220103 124046 worker: -- Audio debug
20220103 124046 worker: ALSA cards: (0:b1 | 1:Headphones | 2:empty | 3:empty
20220103 124046 worker: MPD config: (1:Pi Headphone jack | mixer:(Headphone) | card:1)
20220103 124046 worker: ALSA mixer actual (Headphone)
20220103 124046 worker: ALSA Headphone volume set to (0%)
20220103 124046 worker: -- System
20220103 124049 worker: Host     (TandJ-Radio)
20220103 124050 worker: moOde    (7.6.1 2021-12-17)
20220103 124050 worker: RaspiOS  (10.6)
20220103 124050 worker: Kernel   (5.4.77-v8+ #1371)
20220103 124050 worker: Platform (Pi-3B 1.2 1GB)
20220103 124050 worker: ARM arch (aarch64, 64-bit kernel)
20220103 124050 worker: MPD ver  (0.23.4_p0x3)
20220103 124050 worker: CPU gov  (ondemand)
20220103 124050 worker: USB boot not enabled yet
20220103 124050 worker: File system expanded
20220103 124050 worker: HDMI port off
20220103 124050 worker: -- Network
20220103 124050 worker: IP address check timeout (90 secs)
20220103 124050 worker: eth0 adapter exists
20220103 124050 worker: eth0 IP address check (No)
20220103 124050 worker: IP addr (192.168.7.157)
20220103 124050 worker: Netmask (255.255.255.0)
20220103 124050 worker: Gateway (192.168.7.1)
20220103 124050 worker: Pri DNS (fe80::7edb:98ff:fe22:e31f%eth0)
20220103 124050 worker: Domain  (192.168.7.1)
20220103 124050 worker: wlan0 adapter does not exist
20220103 124050 worker: -- Audio config
20220103 124050 worker: MPD conf update skipped (USB device)
20220103 124050 worker: ALSA card number (1)
20220103 124050 worker: MPD audio output (Pi Headphone jack)
20220103 124050 worker: Audio formats (U8, S16_LE)
20220103 124050 worker: ALSA mixer name (Headphone)
20220103 124050 worker: MPD mixer type (software)
20220103 124050 worker: Hdwr volume controller exists
20220103 124050 worker: Max ALSA volume (100%)
20220103 124050 worker: ALSA output mode (Default: plughw)
20220103 124050 worker: ALSA loopback (Off)
20220103 124050 worker: Reset renderer active flags
20220103 124051 worker: CamillaDSP (off)
20220103 124051 worker: -- MPD startup
20220103 124051 worker: MPD started
20220103 124052 worker: MPD accepting connections
20220103 124052 worker: MPD output 1 ALSA Default (on)
20220103 124052 worker: MPD output 2 ALSA Bluetooth (off)
20220103 124052 worker: MPD output 3 HTTP Server (on)
20220103 124052 worker: MPD crossfade (off)
20220103 124052 worker: MPD ignore CUE files (yes)
20220103 124052 worker: -- Feature availability
20220103 124052 worker: Source select (available)
20220103 124052 worker: Source select (source: MPD)
20220103 124052 worker: Source select (output: Pi Headphone jack)
20220103 124052 worker: Bluetooth (available)
20220103 124052 worker: Airplay renderer (available)
20220103 124052 worker: Spotify renderer (available)
20220103 124052 worker: Squeezelite (available)
20220103 124052 worker: RoonBridge renderer (not installed)
20220103 124052 worker: Multiroom sender (available)
20220103 124052 worker: Multiroom receiver (available)
20220103 124052 worker: UPnP renderer (available: started)
20220103 124052 worker: DLNA server (available)
20220103 124052 worker: UPnP browser (available)
20220103 124052 worker: GPIO button handler (available)
20220103 124052 worker: Stream recorder (n/a)
20220103 124052 worker: -- Music sources
20220103 124052 worker: USB source (T and J's Radio)
20220103 124052 worker: NAS and UPnP sources (none configured)
20220103 124052 worker: -- Other
20220103 124052 worker: USB volume knob (Off)
20220103 124052 worker: Shellinabox SSH started
20220103 124052 worker: USB auto-mounter (udisks-glue)
20220103 124052 worker: LED0 (On)
20220103 124052 worker: LED1 (On)
20220103 124052 worker: Saved MPD vol level (0)
20220103 124052 worker: Preamp volume level (0)
20220103 124052 worker: MPD volume level (0) restored
20220103 124052 worker: ALSA Headphone volume (100%)
20220103 124052 worker: Auto-play (Off)
20220103 124052 worker: Maintenance interval (3 hours)
20220103 124052 worker: Screen saver activation (Never)
20220103 124052 worker: Session permissions (OK)
20220103 124053 worker: Watchdog started
20220103 124053 worker: Ready
20220103 124832 watchdog: Info: Reducing PHP fpm worker pool

	

I

**Comment by moodeaudio** [comment]
Your best bet is to post the issue in the Support section of our Forum. Our Git repos are mainly for developer issues.

**Comment by tokenwizard** [comment]
I tried to post there, but it says no new registrations are allowed. Since I can't register, I can post.

**Comment by moodeaudio** [comment]
Right, I forgot registrations are disabled to curb spam.

Email tim at moodeaudio dot org with your desired userid and I'll create an account for you.

**Comment by jbrask** [comment]
I am experiencing a similar issue, also with an ext4 formatted USB. Did you manage to find a solution? If it was posted in the support forum, could you post a link here?

Thanks!
