### ISSUE TITLE
pls file structure

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#48]
The pls files constructed by `/var/www/command/moode.php` are slightly incorrect in ways which apparently don't affect MPD.

An example is:

```
pi@moode:/var/lib/mpd/music/RADIO $ cat Zen\ FM.pls
[playlist]
numberofentries=1
File1=http://lb.zenfm.be/zenfm.mp3
Title1=Zen FM
Length1=-1
version=2
```

which should be
```
pi@moode:/var/lib/mpd/music/RADIO $ cat Zen\ FM.pls
[playlist]
File1=http://lb.zenfm.be/zenfm.mp3
Title1=Zen FM
Length1=-1
NumberOfEntries=1
Version=2
```
where `NumberOfEntries=` and `Version=` are the closing lines and are in Pascal Case.

Starting from my fork of the `develop` branch, I've created a new branch `fix-pls-format`, and in it modified moode.php. Will create a PR shortly.

Note that this is as much a test of my ability to do a PR on the moOde repo as it is a trivial fix to moode.php. Hence the longish explanation.

References:

[WinAmp](http://forums.winamp.com/showthread.php?threadid=65772)

[Wikipedia](https://en.wikipedia.org/wiki/PLS_(file_format))

**Comment by monkeypox** [comment]
Just curious (Tim), is there a reason moode uses pls here and m3u for saved playlists or is it just legacy code and momentum?

**Comment by monkeypox** [comment]
Sorry to drag this ot, will continue on the forum.

**Comment by moodeaudio** [comment]
PR merged
