### ISSUE TITLE
problem with bluetooth - pair but doesn't connect

### ISSUE THREAD

**Issue by georgew21** [moode-player/moode#484]
Hello, 

I would like to use bluetooth renderer but I can't. I pair my tv/laptop/android phone but then I can't connect the device. The problem as far as I understand is that my devices don't "recognize" moode as a render/ player and even if my laptop connects doesn't send audio. 

I have tried a lot restarts , enable disable bt adapters etc but no result. 

this is link to system info: https://pastebin.pl/view/55901921

*the last log files are produced by my attemps to connect my tv to moode

**Comment by moodeaudio** [comment]
Hi,

I don't do any application support in Github just dev stuff but if you email tim at moodeaudio dot org with the userid you would like to use on our support Forum I'll setup an account for you. You can then post an issue in the Support section of the Forum and someone will try to help you out.

-Tim
