### ISSUE TITLE
"trigger" sql statements missing from moode-sqlite3.db.sql

### ISSUE THREAD

**Issue by swinokur** [moode-player/moode#487]
In the course of debugging an unrelated issue, I wanted to go back to a clean database.

```
# cd /var/local/www/db
# sqlite3 moode-clean.db < moode-sqlite3.db.sql
```
I then moved the current database out of the way and moved the clean one into place as moode-sqlite3.db.

After rebooting I saw that the startup had failed the integrity check with a value of (1).
This appears to indicate that the trigger is missing from the database.

I dumped the old database to retrieve the trigger and added that to my clean database:
```
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TRIGGER ro_columns BEFORE UPDATE OF param, value, [action] ON cfg_hash FOR EACH ROW BEGIN SELECT RAISE(ABORT, 'read only'); END;
COMMIT;
```

Rebooting again the database started properly. It seems like 
```
CREATE TRIGGER ro_columns BEFORE UPDATE OF param, value, [action] ON cfg_hash FOR EACH ROW BEGIN SELECT RAISE(ABORT, 'read only'); END;
```
should be added to moode-sqlite3.db.sql?

**Comment by moodeaudio** [comment]
All the hash stuff is gone in upcoming moOde 8 :-)
