### ISSUE TITLE
Audio over Rpi3+ headphone jack stops after 1 minute of music

### ISSUE THREAD

**Issue by skerit** [moode-player/moode#497]
I'm trying to stream some radio stations, but after 1 minute the audio just stops.
I don't see anything special in the interface: the counters keep on going without any sound coming out of the headphone jack.

The same also happens with spotify connect: 1 minute of audio and then nothing.

I don't see anything special in the logs. `dmesg` does not complain about undervoltage, there are no errors in the `moode.log` file.

Any ideas? :/

**Comment by moodeaudio** [comment]
I only use Git issues for developer related things. Your best bet is to post on the Moode Forum https://moodeaudio.org/forum in the Support section. Email tim at moodeaudio dot org with your preferred userid and I'll create an account for you.

Include the moode startup log in your post using the command below so we know something about your config.
```
moodeutl -l
```

-Tim
