### ISSUE TITLE
Pi Zero W doesn't see or connect to WiFi on channel 13

### ISSUE THREAD

**Issue by iedex** [moode-player/moode#502]
Hi, I installed Moode (v8.0.1) on a Pi Zero W. From AP mode, it sees other networks/SSIDs, but not mine. Maybe because is running on channel 13. I've set the country everytime, in my country is allowed.
On the same Pi I've installed latest RaspberryPi OS Lite, and it sees and connects to my WiFi. What could ne the problem?

**Comment by moodeaudio** [comment]
You will need to post on our support Forum. I only use Got issues for developer stuff.
Visit http://moodeaudio.org support section and request an account.
