### ISSUE TITLE
6.2 airplay and upnp not working

### ISSUE THREAD

**Issue by daxiawj** [moode-player/moode#51]
When I upgrade to 6.2, the airplay and upnp not working.
My moode is connect to a USB DAC, and when I play music in moode (eg. play radio or files in moode drive), it works great.
While airplay used, there isn't any sound even I turn every device's volume to maximum.
While upnp used from my android phone, it gives some 1 second strange sound and then stop, and my phone tells me the DLNA device not working..

What would the problem is ?Thanks

**Comment by moodeaudio** [comment]
For Airplay try setting a different bit depth in Airplay Config. Maybe your DAC only accepts a certain bit depth.

For the UPnP issue I'd recommend posting it in the support section of the moOde Forum.
