### ISSUE TITLE
Feature request: better support for USB Ethernet gadget mode

### ISSUE THREAD

**Issue by the4anoni** [moode-player/moode#510]
Hi
Like in topic - can moode audio be more adjusted by default to be used with usb gadget mode?

For example can it be set by default to use static MAC address and not change it every reboot and to add usb gadget mode settings to Web UI?

I wanted to make request on forum, but for some reason my account is not working.

**Comment by moodeaudio** [comment]
After your account was created you should have received an email with instructions on how to login and make a first post within 2 days to avoid having the account auto-purged.

Email tim at moodeaudio dot org with your preferred userid and I can create another account for you but be sure to make a first post within 2 days.
