### ISSUE TITLE
Is cron disabled in 8.02 on purpose?

### ISSUE THREAD

**Issue by kongwak** [moode-player/moode#513]
Hi,
This is more of a request for information. 

I am planning to run a script to generate daily random play lists, but I have noticed that when I boot my Raspberry Pi, cron is inactive as seen below. This is consistent behavior. Is this by design?

```
sudo systemctl status cron
● cron.service - Regular background program processing daemon
     Loaded: loaded (/lib/systemd/system/cron.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: man:cron(8)

```

System Info
```
moOde release		= 8.0.2 2022-03-25
RaspiOS			= 11.2
Linux kernel		= 5.15.28-v7+ #1532
Platform		= Pi-3B 1.2 1GB
Architecture		= armv7l (32-bit)
```
Thanks for your help

**Comment by moodeaudio** [comment]
For information on how moOde is built including how services are configured refer to the pkgbuild repo.
https://github.com/moode-player/pkgbuild/tree/main/packages/moode-player
