### ISSUE TITLE
Request: Duck audio instead of pausing it when multiple sources are playing at once

### ISSUE THREAD

**Issue by tamahau30494** [moode-player/moode#514]
It would be great to have an option to have audio volume be lowered instead of paused. Specifically if I am streaming music via AirPlay, I would like that volume to lower while MPD plays something.

This would be like playing music on a mobile device and GPS directions be read over top of the music.

**Comment by moodeaudio** [comment]
Not possible. moOde routes audio from MPD or renderer directly to the output device and not through a central volume mixer which would degrade audio quality.
