### ISSUE TITLE
Cannot enable Bluetooth using RPI0W

### ISSUE THREAD

**Issue by bahamut657** [moode-player/moode#516]
Hi all and thanks for the wonderful work.

I notice that after upgrading my RPI0w from Moode7 to Moode8, Integrated Bluetooth stops working.

If enabled from WEB, the UI remains in waiting state.
If from bash I try to launch hciconfig command I obtain this error:
`
Can't open HCI socket.: Address family not supported by protocol
`
Looking on dmesg:
`
bluetooth: Unknown symbol aes_expandkey (err -2)
bluetooth: Unknown symbol aes_encrypt (err -2)
`
Best Regards

**Comment by moodeaudio** [comment]
Hi,

Your best bet is to get an account on our support Forum and post in the Support section where someone with a Zero W can try and repro the issue. I can set up an account for you, just let me know your preferred user id.
