### ISSUE TITLE
System reboot due restoring backup 

### ISSUE THREAD

**Issue by AlfredoCubitos** [moode-player/moode#517]
The system reboots when a backup restore from an older vision is performed, where all options are enabled.
Restore Radio Stations only returns ok, but no Radio Station is restored.
So, restoring an old backup form the current version does not work :-(

**Comment by moodeaudio** [comment]
You best bet is to post the issue in the support section of our Forum. Email tim at moodeudio dot org with your preferred userid and I'll setup an account for you.
