### ISSUE TITLE
Moode audio Control im home assistant.

### ISSUE THREAD

**Issue by kuduacz** [moode-player/moode#518]
I have a problem with control moode audio from HA.
I set metadata file to on in system configuration in moodeaudio.

Mirror link current song.txt file by command:
sudo ln /var/local/www/currentsong.txt /var/www/currentsong.txt command.

create sensor in HA:

    - platform: command_line
      name: Moode Renderer
      command: curl http://moode.local/currentsong.txt | sed -n 's/^file=//p'
      value_template: >-
        {% if value == 'Airplay Active' %}
        Airplay
        {% elif value == 'Bluetooth Active' %}
        Bluetooth
        {% elif value == '' %}
        Brak
        {% else %}
        MPD
        {% endif %}
      scan_interval: 15
 
    - platform: command_line
      name: Moode MPD State
      command: curl http://moode.local/currentsong.txt | sed -n 's/^state=//p'
      value_template: >-
        {% if value == 'play' %}
        Play
        {% elif value == 'pause' %}
        Pause
        {% elif value == 'stop' %}
        Stop
        {% else %}
        Brak
        {% endif %}
      scan_interval: 15

And IT work till i change render. I mean when i play  internet radio and change station mirrored file have no change. 
I try to use that file to better Control IT by Home assistant to see actual render like BT or airplay.
why mirrored file doesn't changed?

**Comment by moodeaudio** [comment]
Your best bet is to post the issue in the support section of our Forum. Email tim at moodeudio dot org with your preferred userid and I'll setup an account for you.

**Comment by rvandet** [comment]
Did you progress on your issue?

I would like to control all sort of music sources (Spotify, MPD, iTunes, SMBv1) from HA.
iTunes offcourse is a no go yet, but the others should be aware of what is playing making it wife-friendly.

**Comment by kuduacz** [comment]
unfortunetaly not, still no progress.
