### ISSUE TITLE
Clicking noise when switching tracks

### ISSUE THREAD

**Issue by manu-g** [moode-player/moode#519]
Hello,
I couldn't find any fitting issues already posted to this issue.
When switching tracks on Spotify or starting/stopping/switching radio stations, there is a clicking noise occuring.
I could not find any setting in the moode config that would resolve this issue.
Is this issue known?
What further information/config/settings would you need from me to verify this?
Best regards

**Comment by moodeaudio** [comment]
Your best bet is to post the issue in the support section of our Forum. Email tim at moodeudio dot org with your preferred userid and I'll setup an account for you.
