### ISSUE TITLE
spotify  does not output audio if ALSA output mode is HW

### ISSUE THREAD

**Issue by noam1023** [moode-player/moode#524]
short: On my system  Spotify stopped playing and disconnected from my phone after pressing pause in the phone.
While connected, the sound is not heard. (Using moode directly to play music using Radio stations works fine)

workaround: Changed  "Audio Config" | "Alsa Options"  |"Output mode" to "Default plugHW"

Up until about March everything worked great, so I suspected the cause is similar to other threads (https://moodeaudio.org/forum/showthread.php?tid=4772&highlight=spotify) but changing the IP did not help.

Note: For debugging I found /var/www/inc/playerlib.php and enabled the verbose flag

System used:
RPI 3B+, moode 7.5.0 (tested also on 7.4) , output to DAC (CambridgeAudio)
Phone (used as remote control): Xiaomi M10T, running spotify 8.7.38.664

**Comment by moodeaudio** [comment]
Troubleshooting is handled in the Support section of our Forum https://moodeaudio.org/forum to give all of our users the opportunity to participate and benefit from the discussion. We only use Git for developer related issues.

Email tim at moodeaudio dot org with your preferred userid and I'll be happy to setup an account for you.
