### ISSUE TITLE
GUI flaws

### ISSUE THREAD

**Issue by jiemdev** [moode-player/moode#528]
Hi,

First of all, thanks for this very good player.
Now, I meet some faults in UI, listed here. They can be seen as bugs or requests.
My setup : Rpi 4 + official 7'' touchscreen (square pixels param enabled, see picture), Moodeaudio v8.1
![IMG_20220627_131929864](https://user-images.githubusercontent.com/69395205/177277671-ea5854eb-5408-4787-bc5a-677389268d7d.jpg)

### 1-
![IMG_20220627_131842647](https://user-images.githubusercontent.com/69395205/177277942-910297b4-d51c-4be1-8725-e52b61cf2558.jpg)
- Playlist at left side: durations are not well aligned, and songs name are sometimes shortened a lot (only 2 or 3 characters!)
- Bottom icons in the middle part are very close to screen limit, making them hard to use (and are quite small)

### 2-
![IMG_20220627_131828121](https://user-images.githubusercontent.com/69395205/177278165-46cab8ba-2ded-401e-9287-b5097690019c.jpg)
- I don't see any change when using big font sizes (For me, large buttons and text on touchscreens is very important, making them lot easier to use)
- plus, in this screenshot, we can see part of a rectangle drawn on top-right side

### 3-
![IMG_20220627_131649385](https://user-images.githubusercontent.com/69395205/177280406-12796071-90e1-4683-8942-6a9fa891af49.jpg)
![IMG_20220627_131723399](https://user-images.githubusercontent.com/69395205/177280449-1effbac4-bfe5-44a4-b605-01979c7d65b5.jpg)
- In first screenshot, we have 9 different configuration settings access. In second screenshot, we find only 4 tabs at the top to access to configuration screens.
- plus, in first screenshot, we can see part of a rectangle drawn on right side

### 4-
![IMG_20220627_131803462](https://user-images.githubusercontent.com/69395205/177279444-811d9224-b971-4aae-8b8a-54e6f2253607.jpg)
![IMG_20220627_131744129](https://user-images.githubusercontent.com/69395205/177279497-0f750f5d-a6f5-4b5d-b9c1-2932b39425bb.jpg)
- suggestion: "m" menu, does it need to be different in config or player screen? If yes, are "audio info" and "refresh" useful when in setup screens? And, could we fuse "Configure" with "Preferences" to shorten the list of choices (first picture)?

Thanks for reading.
Best

**Comment by moodeaudio** [comment]
Troubleshooting and support is done in our Forum so all our users can benefit from the discussion. The project only uses Git for developer related issues. Email tim at moodeaudio dot org with your preferred userid and I'll be happy to create an account for you.
