### ISSUE TITLE
Impossible to remove radio stations

### ISSUE THREAD

**Issue by kromsam** [moode-player/moode#530]
As I want to have control over what radio stations I want to have and which I don't want to have, I tried to remove all radio stations from Moode to start with a blank slate. These are the steps I followed:

1. Remove contents of these directories:
```
/var/lib/mpd/music/RADIO
/var/local/www/imagesw/radio-logos
/var/local/www/imagesw/radio-logos/thumb
```

2. Regenerate the music library
3. Empty the browser cache
4. Update music library

This removes all the thumbnails and stream-urls form the radiostation, which makes them unusable, but they are still listed:

![Screenshot 2022-07-14 at 13-40-03 FrambloOs](https://user-images.githubusercontent.com/47101903/178974520-48e67329-f133-4ce9-b984-f720df772485.png)

On the Moode forum (https://moodeaudio.org/forum/showthread.php?tid=1255) the following solution is suggested:
`If you are trying to remove the built in radio stations simply switch to Radio view, click the cog icon to open the Radio Manager and for "moOde stations" select "Hide all" `
The problem here is that with this solution, I cannot re-add the stations from Moode that I want to keep, such as 'BBC Radio 1', it gives me the following error message:

![Screenshot 2022-07-14 at 13-50-35 FrambloOs](https://user-images.githubusercontent.com/47101903/178976010-30e46f20-11f6-4588-b9f3-4ab8da5b0955.png)

**Comment by moodeaudio** [comment]
Troubleshooting and support is done in our Forum so all our users can benefit from the discussion. The project only uses Git for developer related issues. Email tim at moodeaudio dot org with your preferred userid and I'll be happy to create an account for you.
