### ISSUE TITLE
Updating /var/local/www/currentsong.txt 

### ISSUE THREAD

**Issue by lele-sick** [moode-player/moode#531]
When changing the volume with the rotary encoder (handled by /var/www/daemon/rotenc.py) the value of "volume" in the file /var/local/www/currentsong.txt is not updated.

pi@moode:~ $ cat /var/local/www/currentsong.txt | grep volume
volume=46

sqlite> SELECT * FROM cfg_system WHERE id = 32;
32|volknob|40

**Comment by moodeaudio** [comment]
Troubleshooting and support is done in our Forum so all our users can benefit from the discussion. The project only uses Git for developer related issues. Email tim at moodeaudio dot org with your preferred userid and I'll be happy to create an account for you.
