### ISSUE TITLE
Minidlna: Inotify

### ISSUE THREAD

**Issue by vrenaville** [moode-player/moode#537]
Hello

Thanks for moode, It's really great :)
I have start using it to share music with kitchen radio (frontier silicon)  radio.
I have a small issue, when I want to add news song / playlist, I need to rebuilt the all database.
toggle to yes inotify solved the issue, I have prepare a PR, I will need to test it on a fresh install
in case you see an interest for it, and I can also try to add a toggle button to enable it if needed

Thanks for your work

https://github.com/moode-player/moode/pull/536

**Comment by moodeaudio** [comment]
Will reopen if OP still has interest
