### ISSUE TITLE
Add firmware files for Realtek Bluetooth chipset rtl8761bu

### ISSUE THREAD

**Issue by ptandler** [moode-player/moode#541]
The bluetooth on my Pi 4 is broken, so I bought a USB Bloothoth adapter with an external antenna to get a better range. The one I got claimed to have the rtl8761b chipset, but it turned out that it has rtl8761bu. And bluethooth failed to start.

In the syslog I found that `rtl8761bu_fw.bin` and `rtl8761bu_config.bin` are missing (current moOde 8.1.2 with kernel 5.15).

After browsing syslog and ~~googling~~ [ecosia-ing](https://www.ecosia.org/) a while, I found that [these have been added to the kernel June 2021](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=64f02a260ef8bd9e0d1dad369ef376338045d15b). However, I didn't find them in a raspberry pi package (did I miss something?), but I finally found these files contained in [Ubuntu's firmware package](https://packages.ubuntu.com/jammy/linux-firmware) and as this page says that these are for all architectures (I actually have no idea what's contained in these files... :thinking:), I extracted them and copied them to the Raspbarry Pi. And it works well: Now, I can **finally** also stream music from other devices via Bluethooth to moOde! Thank you so much for this very cool system!!

In case someone wants to try as well:

```bash
# download linux-firmware_20220329.git681281e4-0ubuntu1_all.deb from mirror of your choice
# see https://packages.ubuntu.com/jammy/all/linux-firmware/download
# e.g. for Germany
wget http://de.archive.ubuntu.com/ubuntu/pool/main/l/linux-firmware/linux-firmware_20220329.git681281e4-0ubuntu1_all.deb

# extract data archive
ar x linux-firmware_20220329.git681281e4-0ubuntu1_all.deb data.tar.zst

# extract driver files (or whatever these are)
tar xf data.tar.zst --wildcards '*rtl8761bu*'

# copy to system location
sudo cp rtl8761bu_* /usr/lib/firmware/rtl_bt/
```

So, maybe you want to include these files in the moOde images to support this bluetooth chipset.

(Or would it make sense to request this for the upstream raspberry pi packages?)

**Comment by moodeaudio** [comment]
Generally we leave wifi / bt drivers up to the Raspberry Pi project. Your best bet would be to post an issue in the Raspberry Pi kernel git and see if they will include it. Then eventually it will appear in a kernel shipped with moOde.
