### ISSUE TITLE
Feature: Suspend USB DACs

### ISSUE THREAD

**Issue by sll552** [moode-player/moode#546]
It would be nice to have the possibility to automatically suspend the usb power after some timeout with no interaction/playback. Background is that most USB DACs do not suspend themselves and stay on all the time, that means that e.g. display stays on etc. 

For a RPi this can be achieved with [uhubctl](https://github.com/mvp/uhubctl) but it disables *all* USB Ports.

I have scripted this myself but I had to use the mpd events which is technically a little too late in the reactivation use case. Meaning that mpd fails to open the device and i have to press play again to make it work. 

So the proposed feature would be either 

#### more generic: Hook support for different events (playstate, library update, settings changed, etc.)
Add some setting to call a script/binary when a defined event happens before calling mpd. Maybe add some environment variables with information about the specific event when calling the script/binary.

#### USB suspend: Automatically cut power to USB after some idle time
Add a setting to suspend an USB hub/port with a configurable timeout. At least for RPi there needs to be a warning that all USB ports will  be deactivated (e.g. keyboards/mice, wifi dongle, etc. will also be deactivated).

**Comment by moodeaudio** [comment]
Your best bet is to post in our Forum and see what kind of feedback your proposal gets. Email tim at moodeaudio dot org with your preferred userid and I'll be happy to create an account for you.
