### ISSUE TITLE
Playlist doesn't show the name of the radio station

### ISSUE THREAD

**Issue by biva** [moode-player/moode#547]
Hello,
I use 8.2.0 and have some custom radio playlist. For example:
```
#EXTM3U
#EXTINF:0,FIP Electro
http://icecast.radiofrance.fr/fipelectro-hifi.aac
#EXTINF:0,FIP Groove
http://icecast.radiofrance.fr/fipgroove-hifi.aac
```

Unfortunately, the name of the station is not displayed (both on the Web UI and on MALP). Instead, I see the URL only (`fipelectro-hifi.aac`).

I have the feeling, not confirmed, that it worked in versions before 8 of Moode. I have read https://github.com/moode-player/moode/issues/173 and https://github.com/moode-player/moode/issues/73 but I'm not sure to understand. Would you have an idea how to solve this?

**Comment by moodeaudio** [comment]
Troubleshooting is handled in the Support section of our Forum so that all our users can benefit from the discussion. Auto registrations are closed due to excessive amounts of bot-spam and bot-accounts.

Let me know your preferred userid and I'll be happy to create an account for you.
