### ISSUE TITLE
Commands executed by the GPIO Button Handler have root privileges

### ISSUE THREAD

**Issue by spontanurlaub** [moode-player/moode#549]
All commands that are executed through the GPIO Button Handler have access to root privileges. This could allow for easy root access on the raspberry pi by opening the web interface and waiting for the user to press the button. Only network access is required for that. Please check if it would be possible to execute the commands without root.

**Comment by moodeaudio** [comment]
What is the real world usage scenario that makes this a security concern?

**Comment by moodeaudio** [comment]
Closed du to lack of response to my question.
