### ISSUE TITLE
Root File System Not Expanded

### ISSUE THREAD

**Issue by NotYourAverageAl** [moode-player/moode#550]
Hi Tim,

Hope to get some assistance please. My sdcard is 32gb but the root file sys has not auto expanded.
Any ideas on how to fix?
![image](https://user-images.githubusercontent.com/24758479/194479387-819e442c-d291-4722-8728-df3992343a53.png)

**Comment by moodeaudio** [comment]
Support and troubleshooting is handled in our Forum so everyone can benefit from the discussion.  I use Git issues mainly for developer related stuff.

Email tim at moodeaudio dot org with your preferred userid and I'll be happy to setup a Forum account for you :-)
