### ISSUE TITLE
2 trivial corrections to moOde 8.2.1 codebase

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#553]
These don't seem to merit being separate issues.

1) /boot/moodecfg.ini.default 
This file continues to be headlined 
```
; Moode Release : 8.0.0 2022-03-12
; Create date	: 2022-03-12 14:30:51
```
though we're now up to release 8.2.1 in October.

2) /var/www/inc/renderer.php
This script starts shairport-sync with -vvu flags when in moOde's debug logging mode. The -u flag is deprecated and not needed according to the help output from shairport-sync (4.1-dev-600-g97fa75e8).

**Comment by moodeaudio** [comment]
1. Thats ok since in practice user would prolly use moodeutl -e to generate a current file.
2. Fixed
