### ISSUE TITLE
Bluetooth keeps disconnecting - Moode 8.2.1

### ISSUE THREAD

**Issue by Menimm** [moode-player/moode#580]
Hi,

Using Moode 8.2.1 on RPI 3B+ with a DAC, I have everything working but bluetooth keeps disconnecting.
Once it disconnects - it will not connect again until I restart the bluetooth service from the renderers UI. 

Same issue was also on 7.x latest.

Meni

**Comment by moodeaudio** [comment]
Troubleshooting is provided in the Support section of our Forum so that our user community can benefit from the discussion. Email tim at moodeaudio dot org with your preferred userid and I'll setup an account for you.
