### ISSUE TITLE
sysutil.sh doesn't clear winbindd log file(s)

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#593]
`winbindd` is part of the samba suite. In moOde the `winbindd` process logs to `/var/log/samba/log.wb-HOSTNAME`, so, for example, `log.wb-MOODE`. I haven't been able to find where the logfile name gets configured.

`/var/www/util/sysutil.sh` resets log files created by the samba suite:

```
pi@m824p3a:~ $ grep samba /var/www/util/sysutil.sh
	truncate /var/log/samba/log.nmbd --size 0
	truncate /var/log/samba/log.smbd --size 0
	rm /var/log/samba/log.*.* 2> /dev/null
```
I don't know why both `truncate` and `rm` are used but the regular expression in the `rm` command misses the `winbindd` log(s). For example:

```
pi@m824p3a:~ $ ls -l /var/log/samba
total 1076
drwx------ 3 root root    4096 Dec 18 15:36 cores
-rw-r--r-- 1 root root       0 Jan 10 09:27 log.nmbd
-rw-r--r-- 1 root root       0 Jan 10 09:27 log.smbd
-rw-r--r-- 1 root root 1092946 Jan 10 09:29 log.wb-M824P3A
-rw-r--r-- 1 root root     844 Dec 18 15:37 log.wb-MOODE
-rw-r--r-- 1 root root       0 Jan  8 00:00 log.winbindd
```
There are two `winbindd` log files because I had changed the hostname from MOODE to M824P3A on Dec 30. In general, there will be as many log files as there have been HOSTNAMEs. None gets removed or reset to zero length.

The content of the `log.wb-MOODE` file runs from my configuration of samba (Dec 18) to Dec 30 and of the `log.wb-M824P3A` file from Dec 30 to today (Jan 10). 

The winbindd log file grows modestly with a few lines added every 5 minutes of the kind
```
[2023/01/10 09:39:06.548872,  0] ../../source3/rpc_server/rpc_ncacn_np.c:454(rpcint_dispatch)
  rpcint_dispatch: DCE/RPC fault in call lsarpc:32 - DCERPC_NCA_S_OP_RNG_ERROR
[2023/01/10 09:39:06.550167,  0] ../../source3/rpc_server/rpc_ncacn_np.c:454(rpcint_dispatch)
  rpcint_dispatch: DCE/RPC fault in call lsarpc:32 - DCERPC_NCA_S_OP_RNG_ERROR
```
This error has been discussed in the past in the moOde Forum; Internet wisdom is that it is harmless.

I suggest adding a third `truncate` line to sysutil.sh
```
	truncate /var/log/samba/log.nmbd --size 0
	truncate /var/log/samba/log.smbd --size 0
	truncate /var/log/samba/log.wb-* --size 0
```

---

ISTR that this winbindd process is needed by samba even if NT servers are not involved but I plead ignorance of the details.

**Comment by moodeaudio** [comment]
I'll post a commit today.
