### ISSUE TITLE
Set Output to Mono

### ISSUE THREAD

**Issue by vincss** [moode-player/moode#595]
Hi !
First of all, thanks for this great project !
Second, I think the forum would be more appropriate for this ask for help, but I cannot register on it. 
`Sorry, but you cannot register at this time because the administrator has disabled new account registrations.`

So, there is my question.
I've got a Raspberry Pi Zero W 1.1 and a HifiBerry MiniAmp (running on moOde 8.4.2) wired to a single speaker (an old radio).
I've done some search for it, I found two ways to do it :
- Change a setting in the MPD player : https://moodeaudio.org/forum/showthread.php?tid=3412&highlight=mono
=> When I try to change that settings, it's not applied, and the value is rollback.
=> It wouldn't work for Spotify & Bluetooth playback.
- Doing some ALSA configuration : https://support.hifiberry.com/hc/en-us/community/posts/360013981717-HOWTO-Send-mono-to-both-speaker-
=> It doesn't seems to apply either.

Do you have another suggestion, way of doing ?
Thanks again.

**Comment by moodeaudio** [comment]
I just ran a quick test on latest release setting resampling Enabled to Yes and Channels to Mono and no issues.
