### ISSUE TITLE
bump to bluez-alsa v4.0.0

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#602]
moOde 8.2.5 includes bluez-alsa V3.0.0 built as "backport" according to the moode-player/pkgbuild repo.

I've just built bluez-alsa V4.0.0 from source taken directly from the github repo. Installed it into a moOde 8.2.5 player and so far everything seems good to go. (ETA- so far, tested only as a sink. Will start testing as source tonight.) 

Get a new utility bluealsa-cli in the bargain.

Suggest bluez-alsa v4.0.0 be a candidate for moOde. Didn't see it mentioned in recent announcement of upcoming moOde 8.3.0 release.

**Comment by moodeaudio** [comment]
Nice :-) You and @bitkeeper must have done a mind meld because he just uploaded a blues-alsa 4.0.0 package to our CS repo https://cloudsmith.io/~moodeaudio/repos/m8y/packages/

I haven't tested it yet but your results are a good omen. I'll add it to the r830 relnotes/

**Comment by bitkeeper** [comment]
The build scripts in the pkgbuild repo are commited and pushed.

btw I see already 10 downloads for it. @TheOldPresbyope @moodeaudio are you both testing that much or are already other people 'testing' for us ;-)

**Comment by moodeaudio** [comment]
I installed the two packages on my 5 systems :-)
