### ISSUE TITLE
Use hardware mixer in librespot

### ISSUE THREAD

**Issue by morphZ** [moode-player/moode#607]
When using moode together with Spotify and an alsa hardware mixer I observe, that moode sets the hardware volume to 100 and uses soft mixer in librespot controlled by the Spotify client. This leads to some problems e.g. very loud sound when switching back to moode radio streams via mpd protocol.

Recent versions of librespot support using alsa hardware mixer natively. I verified it is working in another setup. It's easy to setup with cmd args.

How about to change moode so that it uses the same hardware mixing device in Spotify mode and regular mode?

**Comment by moodeaudio** [comment]
When switching from a Spotify session back to MPD the event script `/var/local/www/commandw/spotevent.sh` which is executed by librespot resets ALSA volume back to a level corresponding to the value of the moOde volume knob.

Your best bet is to post this issue in the Support section of our Forum so someone can try and repro it. If you don't have a Forum account email tim at moodeaudio dot org with your preferred userid (at least 5 chars) and I'll create one for you.
