### ISSUE TITLE
SSH not avaiable on fresh installation

### ISSUE THREAD

**Issue by silelmot** [moode-player/moode#608]
Installed Moode on a fresh sdcard, ssh via terminal is not avaiable.
i can activate it when i create a document called "ssh" directly on the sdcard, but the login name/password-combination pi/moodeaudio does not work.
port i use is 22

login via webterminal in moode-ui doesnt work either with the given combination of  pw/username

**Comment by moodeaudio** [comment]
The official download sites including our Git repo and moodeaudio.org have information on the new security requirements. This information is also part of the release announcement in our Forum.
