### ISSUE TITLE
Right-justified DAC support

### ISSUE THREAD

**Issue by sstefanov** [moode-player/moode#610]
Hello. I can't register in the forum and I write here.
I can't find Right-justified support in moode player. In Raspberry there must be such support.
It will be good if somewhere in DAC selection or overlay selection to add explanation of technical details about selected format.
Also will be good if there is a way to register new users in Moode forum.
Best regards.

**Comment by moodeaudio** [comment]
View the Support section at http://moodeaudio.org for information on how to request a Forum account.
