### ISSUE TITLE
impossible to start moode audio

### ISSUE THREAD

**Issue by Giandj** [moode-player/moode#618]
After writing moode audio 64bit (latest version) on microsd  for raspberry pi4 2gb with a waveshare 7" touch display the display after first boot and expanded on microsd continue to stay on black screen (nothing to display), so I connect to AP Moode with AP password Moodeaudio (this password is not mentioned on setup moode guide, i found it on google).
Moode setup guide is generic too..
Nothing found About if I want to use my touchscreen display (where is the configuration file ?), the screen will not operate so the only method to configure my DAC St400 5122 device is to connect my pc on AP..
Ok but after setup my wifi AP won't connect anymore and my wifi after reboot cannot connect Moode device so moode seems to be inaccessibile (wifi cannot connect device, Access Point wont connect , display wont work, and st400 dac is not present on dtoverlay...) so Moode Audio is completely blocked and not working.
Where is the step by step Guide ?
First of I need the touch screen display must be' always ON after first boot.
Second I don't want to use HDMI or Raspberrypi output Jack to listen audio, I want to activate my DAC ST400 5122 ...and disable all other options...
Third i need to connect Moode Audio via AP and WIFI at the same time (like Volumio).
Moode Audio 64 bit seems a beta release (too many bug), instead Volumio 4.x (latest version) works very well with my hardware, at first starts. 
Why the Moode Audio Guide is not complete? Is there a tutorial ?
Thank you

**Comment by moodeaudio** [comment]
Troubleshooting is provided in the Support section of our Forum. Visit the Support page at https://moodeaudio.org for info on requesting a Forum account.
