### ISSUE TITLE
problem with autodetection and play USB DVD

### ISSUE THREAD

**Issue by Giandj** [moode-player/moode#619]
Hi i have tryed to attach a DVD via usb to my raspberrypi4 but Moode audio player cannot mount it and cannot reproduce CD or DVD songs , maybe there is no function to play a DVD /CD songs ?
Let me know if there is a software bug or if CD/DVD player is unsupported by Moode
Thank you

**Comment by moodeaudio** [comment]
Troubleshooting is provided in our Forum. See the Support page at moodeaudio.org
