### ISSUE TITLE
New-station logo selection - feature or minor bug?

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#62]
(moOde 6.3) 

The New Station menu allows the user to CHOOSE an logo image for the station entry. The image is uploaded and stored in /var/www/images/radio-logos/, a thumbnail version is created from it and stored in /var/www/images/radio-logos/thumbs/, and then the result is displayed in miniature.

If the user then chooses to CANCEL rather than CREATE the new station entry, the two image files remain behind as orphans. They don't affect the normal operation of moOde and they don't consume much storage but they lead to the following interesting behavior.

If at some later time, the user CREATEs an entry and happens to use the same name but does *not* CHOOSE a logo, the orphaned image files are "automagically" used. 

Whether this behavior would be considered a feature or a bug probably depends on the mindset of the user:)

**Comment by moodeaudio** [comment]
I think it's a bug. Cancel should result in the images being deleted. I'll add to the TODO list.
