### ISSUE TITLE
default volume is set to 0

### ISSUE THREAD

**Issue by gdesmott** [moode-player/moode#625]
I just installed version `8.3.2` on a pi and changed the output device to `Pi Headphone Jack`. I didn't get any sound because the volume was 0, which took me some time to figure out. It seems [I'm not the only one confused by this](https://github.com/moode-player/moode/issues/41) so it may be good to set the default to 100.

**Comment by moodeaudio** [comment]
The volume is set to 0 when changing audio devices as a safety precaution.
