### ISSUE TITLE
Transport controls obscure album art thumbnail

### ISSUE THREAD

**Issue by haecksenwerk** [moode-player/moode#626]
The "skip/play/pause" controls obscure the album art thumbnails in the web interface.

Version 8.3.2 running on a Raspberry 4, web interface tested with Chrome, Safari and Firefox

<img width="492" alt="Bildschirmfoto 2023-05-05 um 11 26 40" src="https://user-images.githubusercontent.com/77981303/236506669-42d39e1d-1c23-4872-ab80-42b5c1416f35.png">

**Comment by moodeaudio** [comment]
It's designed that way to maintain balanced spacing for the three groups  of controls on the Playbar. The tiny thumb is just for quick reference to what is playing.
