### ISSUE TITLE
Cover images not loaded

### ISSUE THREAD

**Issue by haecksenwerk** [moode-player/moode#627]
I have created a music database consisting of music albums that live in separate directories on a USB stick, that is attached to the Raspberry that runs the Moode player. A cover art image is embedded in each mp3 file of the albums, but almost 50% of the albums do not show an image in the album view.

When taking a look into the `/var/local/www/imagesw/thmcache` folder, one can see that placeholder images are stored for the files from which the covers could not be loaded.

I cleared and rebuilt the database and recreated the thumbnail cache a couple of times, but the issue remained unchanged. I also tried the different settings for the thumbnail resolutions plus a cache rebuild, but the same difference.

Since the covers show up in other players like VLC I. e., I wonder if there are some criteria that prevent certain covers from being pulled from the mp3 files?

**Comment by moodeaudio** [comment]
I only use Git for developer related troubleshooting. General support is handled in our Forum so that all our users can view/participate in the discussion. Email tim at moodeaudio dot org with your preferred userid (at least 5 characters) and I'll setup an account for you.

**Comment by haecksenwerk** [comment]
That makes sense. I'll write an email then. Thanks!
