### ISSUE TITLE
undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by danbuntu** [moode-player/moode#628]
Hello

I have done a fresh install of Moode 8.3.2 onto a Raspberry Pi 3. The pi is getting it's ip address via a DHCP reservation.

When I open the web interface I can see the below error in the console. This error is stuck in a loop and keeps appearing - 1300 calls to it at the moment and counting.

I see the same when I open the admin pages and if they do open they then lockup on saving:

```
	playerlib.js:968 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Object.success (playerlib.js:968:32)
    at u (jquery-1.8.2.js:974:30)
    at Object.fireWith [as resolveWith] (jquery-1.8.2.js:1082:7)
    at N (jquery-1.8.2.js:7788:14)
    at XMLHttpRequest.n (jquery-1.8.2.js:8500:8)

```

**Comment by moodeaudio** [comment]
Troubleshooting is provided in the Support section of our Forum so that all our users can benefit from the discussion. 

Email tim at moodeaudio.org with your preferred userid (at least 5 characters) and I’ll create an account for you.
