### ISSUE TITLE
New release version is not seen from player

### ISSUE THREAD

**Issue by sstefanov** [moode-player/moode#630]
Moode player is installed version 8.3.2. When check for new version there is a message:
Software is up to date
New release 8.3.3 is existing here, bit player cannot see it.

As I remember same situation was with previous version and I had to install completely from scratch, losing whole music database.

Here is part of system information page:

S Y S T E M   P A R A M E T E R S

moOde release		= 8.3.2 2023-04-21
RaspiOS			= 11.6
Linux kernel		= 6.1.21-v8+ #1642
Platform		= Pi-3B+ 1.3 1GB
Architecture		= aarch64 (64-bit)
Home directory		= /home/moode

**Comment by sstefanov** [comment]
After little investigation seems that file with latest version is not available. File URL is:
https://raw.githubusercontent.com/moode-player/updates/main/moode-player

**Comment by moodeaudio** [comment]
Official release announcements happen in the Forum

**Comment by sstefanov** [comment]
In the Forum version 8.3.3 is announced as available.
The problem is that moode player cannot find it.

**Comment by moodeaudio** [comment]
You prolly need to clear Browser cache or reboot Router.

**Comment by sstefanov** [comment]
Now it's OK. Thank you!
