### ISSUE TITLE
entire UI freezes when a new SMB or NFS mount is added. needs hard reboot on raspberry pi.

### ISSUE THREAD

**Issue by altecdansing** [moode-player/moode#637]
forum https://moodeaudio.org/forum/forumdisplay.php?fid=7 is not allowed to post
this forum also does not allow registration. 

no place to ask this question. 

entire UI freezes when a new SMB or NFS mount is added. needs hard reboot on raspberry pi.

requires re imaging the SD card. basically unusable state.

**Comment by moodeaudio** [comment]
Visit the Support page at moodeaudio.org for info on easily requesting a Forum account.
