### ISSUE TITLE
Squeezelite uses 'hw:' device directly

### ISSUE THREAD

**Issue by Miroka96** [moode-player/moode#643]
Hi,

I have recognized that Moode Audio configures Squeezelite to directly use the ALSA 'hw:<device-id>' device instead of the more compatible 'plughw:<device-id>' device. I know that this difference is configurable in the Audio settings tab, but only for all other services and renderers.

For me this caused the issue that Squeezelite doesn't work with my sound system natively. I have to manually add an output option to the Squeezelite parameters. Using 'plughw:<device-id>', my sound system suddenly starts working.

Would you mind either making Squeezelite also use the setting from the Audio tab or changing the default device to 'plughw:<device-id>'?

Thank you very much!

Kind regards,
Mirko

**Comment by moodeaudio** [comment]
I've added this to upcoming 8.3.7 release. Refer to commit https://github.com/moode-player/moode/commit/aac78f153264abcc1c9daf2cf6ee5ff1f95e3b4f
