### ISSUE TITLE
 8.3.7 - PI2 - CamillaDSP : Illegal instruction

### ISSUE THREAD

**Issue by iomax** [moode-player/moode#648]
Hi,
It seems that the CamillaDSP binary included in the 8.3.7 image doesn’t work on PI2 1.1 (Illegal instruction). However, manually installing the armv7 v1.0.3 from HEnquist's git repository solves the issue, and everything works as expected.

**Comment by moodeaudio** [comment]
We only support Camilla on Pi-2B v1.2 (64 bit ARM) and higher.
If you open Audio Config you won't be able to enable CamillaDSP on a pi-2B v1.1 (32 bit ARM) The SET button will be disabled.
