### ISSUE TITLE
UI should not block in case an non-bluetooth device is connected (e.g. an input device)

### ISSUE THREAD

**Issue by toruki80** [moode-player/moode#652]
Currently whenever a bluetooth device is connected the website blocks with an overlay "Bluetooth active". This does not make sense when e.g. a keyboard is attached.

I'm not an perl expert, but my guess is that this line must be rewritten: https://github.com/moode-player/moode/blob/develop/www/audioinfo.php#L42

It should query if there is actually an bt audio device connected. e.g. via "bluealsa-aplay -l"

**Comment by moodeaudio** [comment]
Regardless of whether a kbd is attached, when a renderer is connected the only functions permitted are via the buttons on the renderer overlay screen. This is to prevent changing settings that could break the renderer config while its connected.

If you want to discuss this on our Forum to see what other users may think visit the Support page at moodeaudio.org and send in a request for a Forum account.
