### ISSUE TITLE
Servie unit files should not be marked executable

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#659]
The system log/journal is cluttered with warnings about system unit files marked as executable.

In particular, in the moOde 9.0.0 ~pre4 image, the following files are marked 755 but should be 644

```
/etc/systemd/system/bluealsa-aplay@.service
/etc/systemd/system/bluealsa.service
/etc/systemd/system/bt-agent.service
/etc/udev/rules.d/10-a2dp-autoconnect.rules
/lib/systemd/system/shellinabox.service
```

**Comment by moodeaudio** [comment]
Fixed in commit to moode-player package, postinstall.hh file
