### ISSUE TITLE
Option to change the default state (pull-up / pull-down) of GPIO pins

### ISSUE THREAD

**Issue by ralphcrutzen** [moode-player/moode#660]
Current situation: GPIO pins are always configured as input/pull-up.
Desired situation: It would be nice to see an option to change the default pin state to pull-down on the GPIO control page.
Motivation: With some buttons (like some rotary encoders with built-in buttons), the pin is connected to Vin when pushed, so it needs to be connected to a pull-down GPIO pin on the Raspberry Pi.

**Comment by moodeaudio** [comment]
Should the option apply to all pins or should each pin have an option to configure as pull-up or pull-down?

**Comment by ralphcrutzen** [comment]
Each pin is used for a different peripheral, so it would make more sense to set up each pin individually.

**Comment by moodeaudio** [comment]
This has been implemented in upcoming moode 9
