### ISSUE TITLE
Add support for additional rotary encoders

### ISSUE THREAD

**Issue by p-vdp** [moode-player/moode#664]
My radio build has two rotary encoders, one for volume (which works great with standard settings) and one that I want to use for track selection (mpc previous and next commands).

What would it take to add settings/support for one or more rotary encoders to be assigned to mpc commands?

**Comment by moodeaudio** [comment]
I don't have any spare bandwidth but maybe another dev will become interested and volunteer their time and effort to write the code for this.

**Comment by thiscantbeserious** [comment]
This is a 99% python task if you take a look a the rotenc.py script so far (all hard-coded).

That is if you simply want fixed GPIO-Pins with no config. I'd say it would make sense to make this configurable ... for example taking a look at Rotary Encoder II plugin in Volumio ...

https://github.com/moode-player/moode/blob/a89881bbdf57cf9d60212c24bbfa52145c88b146/www/snd-config.php#L236

https://github.com/moode-player/moode/blob/a89881bbdf57cf9d60212c24bbfa52145c88b146/www/daemon/rotenc.py

**Comment by moodeaudio** [comment]
Will reopen if there is new information posted
