### ISSUE TITLE
Add I2C volume control support

### ISSUE THREAD

**Issue by JakeShirley** [moode-player/moode#666]
Similar to a rotary encoder, I'd love to use my radio's old potentiometers using something like a ADS1115 as an ADC.

I feel like the data-driven GPIO button setup is close to what I want, but instead of running a command when a pin state changes I want to run a command with the value as a substituted parameter.

Similar to [gpio_buttons](https://github.com/moode-player/moode/blob/develop/www/daemon/gpio_buttons.py) this might be accomplished easier with [some utility packages](https://github.com/adafruit/Adafruit_CircuitPython_ADS1x15) instead of using something like `i2cget`.

I am pretty new to this whole space, so if anyone things of a way to MITM or somehow still use a potentiometer I am all ears!

Excellent project all in all.

**Comment by moodeaudio** [comment]
I'll reopen if there is more information or interest.
