### ISSUE TITLE
moOde 9.0.3: minor bug in sysinfo.sh

### ISSUE THREAD

**Issue by TheOldPresbyope** [moode-player/moode#667]
`/var/www/sysinfo.sh` invokes `node` without first checking if `node` is installed. On a fresh install of moOde 9.0.3

```rho@red:~ $ sudo /var/www/util/sysinfo.sh|more
/var/www/util/sysinfo.sh: line 503: node: command not found
```
Hence, the output of `moodeutl -s` also leads with the same error message.

**Comment by moodeaudio** [comment]
Fixed in commit https://github.com/moode-player/moode/commit/8223260ef3e7a3801fce0e3cda3a0c39c466bd21
