### ISSUE TITLE
Support UPNP browsing in the UI

### ISSUE THREAD

**Issue by fr2lancer** [moode-player/moode#668]
It would be good if Moode can provide the browsing/playing function to remote / local upnp server and render them in the local  mpd or remote one.

As I like the UI and to use it as a consolidated browsing for all of sources.

**Comment by moodeaudio** [comment]
From 3 years ago: release notes for 2022-06-21 moOde 8.1.0 (Bullseye)

`- UPD: Remove UPnP browser (djmount) which is unsupported on 64-bit RaspiOS`

The djmount repo has been unmaintained for almost 20 years

**Comment by fr2lancer** [comment]
Djmount seems to be sshfs for upnp. Is fliesystem required to be as a input source to mpd or Moode?

**Comment by moodeaudio** [comment]
Djmount was UPnP -> FUSE

The plugin you references has no origin source, license, authors or any other FOSS required parts.
I have no idea what the other async_upnp_client project does that you referenced
