### ISSUE TITLE
Headphone / Jack not present in Audio output choices

### ISSUE THREAD

**Issue by TheFax** [moode-player/moode#675]
I would like to use the Raspberry PI Jack audio output for listen music, but "Jack/Headphone" is not present on the list.
It would seem it should be present by reading the line above that says _"Select from Pi HDMI/Headphone, I2S or USB audio devices"_.
How to enable it?
Solution already tried:
- I tried to set a volume bigger than zero (like mentioned in another closed issue)
- I tried to reboot Moode disconnecting HDMI cable

![No JACK option](https://github.com/user-attachments/assets/b7fb8ba9-ce91-4325-be46-a2fdd3085235)

![No HDMI cable](https://github.com/user-attachments/assets/bdfa3f9c-2581-4d2b-ba94-9c02beb190a3)

**Comment by moodeaudio** [comment]
Menu, Configure, System
Integrated audio
**Kernel mode:** Default vc4-kms-v3d driver for advanced Pi HDMI capabilities.
**Firmware mode**: Legacy snd-bcm2835 driver to support Pi Headphone only configuration. No other audio, video or system features are supported.

**Comment by moodeaudio** [comment]
The issue tracker in this repo is for development related issues, not general support questions. 

If you have further support related questions, request an account on our Support Forum. The link is on the Support page at moodeaudio.org

**Comment by tbrodbeck** [comment]
I have the same issue. For me this seems like a bug - why is HDMI recognized but the headphone jack not?

**Comment by secnigma** [comment]
The same issue is happening intermittently with my setup, where the **Pi Headphones** Audio output goes missing randomly , even if **Firmware Mode (legacy)** is selected.

### **My Configuration:**
**_Hardware :_** Raspberry pi 3b+ 
**_Power Supply:_** Custom Power circuit built around [Hilink HLK-PM01 5v AC-DC SMPS ](https://jlcpcb.com/partdetail/hilink-HLKPM01/C209903)
**_OS:_** RPiOS 12.8 Bookworm 64-bit | Linux: 6.6.62 64-bit
**_MoodeAudio Version:_** 9.0.0
**_Audio output:_** Integrated 3.5mm Headphones Jack in Pi 3b+
**_SDCard_** : 16GB Sdcard (generic). 30% usage
**_Memory Usage_** : 174M/907M


### Current workaround 

To fix this issue, currently the workaround is to do the following:

1. _Go to Moodeaudio WebUI -> Menu -> Configure -> System -> Integrated Audio_

_Change  the mode to **Kernel Mode (default)** from **Firmware Mode (legacy)**_ 

![image](https://github.com/user-attachments/assets/83964311-93b8-4969-b2e8-f2eb75075d9e)


2. _Reboot_

3. _Go to Moodeaudio WebUI -> Menu -> Configure -> System -> Integrated Audio_

_Change  the mode back to **Firmware Mode (legacy)** from **Kernel Mode (default)**_ 


4. _Reboot once again_

5. _Go to Moodeaudio WebUI -> Menu -> Configure -> Audio -> Audio Output -> Output device_

Now the missing **Pi Headphones** menu should be back.

![2024-12-25_23-28](https://github.com/user-attachments/assets/9ae5782e-da45-4b1b-b0c8-e6787777ad4e)

**Comment by moodeaudio** [comment]
Questions and troubleshooting for a release are handled in the Support section of our Forum so that all our users can benefit from the discussion.

Visit the Support page at moodeaudio.org for information on how to easily request a Forum account.
