### ISSUE TITLE
Bigger thumbs on folder view

### ISSUE THREAD

**Issue by TheFax** [moode-player/moode#676]
## Bigger thumbs
I spent a lot of time in order to put the correct **album art** in every album of my collection.
When I browse my NAS, using the "Library -> Folder" view, a great part of the screen of my tablet is showing... nothing!
Is it possible to view a grid with bigger thumbs, more or less like Volumio?

## Screenshot from Moode
![Moode](https://github.com/user-attachments/assets/4a68aa44-7d21-40ac-b5ac-9f65f33ce96a)

## Screenshot from Volumio:
![Volumio](https://github.com/user-attachments/assets/608d9128-e65b-4df0-bfdb-c315b8fdb4d6)

**Comment by moodeaudio** [comment]
The issue tracker in this repo is for development related issues, not general support questions. 

If you have further support related questions, request an account on our Support Forum. The link is on the Support page at moodeaudio.org
