### ISSUE TITLE
 musicpd : use of pause cmd without argument is deprecated.

### ISSUE THREAD

**Issue by ekozan** [moode-player/moode#68]
For reference in case of bug 

https://www.musicpd.org/doc/html/protocol.html#controlling-playback

    pause {PAUSE}
    Toggles pause/resumes playing, PAUSE is 0 or 1.
    The use of pause command without the PAUSE argument is deprecated.

**Comment by moodeaudio** [comment]
Thats an odd one. Do you have any insight into why pause is a toggle?

**Comment by ekozan** [comment]
I haven't read all config of MPD but maybe they got option for play cmd act as an restart at 0:00 the music
so resume play ( pause 0 ) is better in term of stability
But i'm not sure about that

**Comment by moodeaudio** [comment]
Maybe when it breaks moOde we can address :-)
