### ISSUE TITLE
Thumbnails not displayed for large library

### ISSUE THREAD

**Issue by jcor29** [moode-player/moode#682]
Hi
Thumbnails are not displayed properly for large audio lib. (6T)
When you first add a repo with a few thousands of track this works fine
But if you load libraries with over 100000 tracks, thumbail are not rendered properly
This is happens in the web UI
![albums](https://github.com/user-attachments/assets/db25e5b2-3983-4e35-a868-e718ff2c5668)
The sames happens with the tag view
Note: I tried to regenerate thumbnails , this is the same

May be a command or script could be handy to do so (just in case)

**Comment by moodeaudio** [comment]
That screen shot suggests that the thumbnail images were not generated at all. Maybe the thumbnail generator crashed for some reason.

You could try looking in the moode log and MPD log for errors.

**Comment by jcor29** [comment]
Ok, I'll check it out.

Le ven. 13 sept. 2024, 13:50, Tim Curtis ***@***.***> a
écrit :
