### ISSUE TITLE
New feature - library statistics

### ISSUE THREAD

**Issue by jcor29** [moode-player/moode#683]
Hi,
What i found is missing with moode or volumio that there is no library statistics provided 
The number of tracks , albums , number of DSD, mp3, flac  ..
could be valuable informations
Regards
Jacques

**Comment by moodeaudio** [comment]
The stats are printed under the cover in Tag view for all or any part of the collection but of you are looking for a more comprehensive "Collection Analysis" it would need to be developed as some sort of utility. What kind of info are you looking for? 

![Screenshot 2024-09-13 at 7 51 40 AM](https://github.com/user-attachments/assets/ea09948a-d0ef-4486-807f-aa4eee198264)

![Screenshot 2024-09-13 at 7 54 43 AM](https://github.com/user-attachments/assets/e7c54472-ab87-4c3b-94d0-f9a6b527c78c)

![Screenshot 2024-09-13 at 7 56 47 AM](https://github.com/user-attachments/assets/e4b6bbbc-5154-45d4-9a1e-7fe1ebb6de75)

**Comment by jcor29** [comment]
First, thanks for your quick Reply
Yes i'd like more compréhensive statistic
The total of FLAC MP3 (all format supported with mpd)


         MP3 FLAC WV .. ( possibly all format supported with mpd)

Total  <total mp3> <total flac>..

If you click on FLAC for instance you get statistics for  FLAC tracks

   e.g  total group by sampling rate bit rate bit depth

       44,1Khz 16 Bits  | 96Khz 24 Bits  |

          TOTAL1               TOTAL2

and eventually if you click on such TOTAL2

 you get to a track list in 96Khz 24 Bits

Hence, you can choose to listen to a specific quality, this can make sense .

To consolidate all this will be probably be  time consuming , but may be
with a cron

Well this is more or less what i have in mind

Regards

Jacques






For each format the total of track with some sampling and bit rate
Thé same for dsd tracks total  by type dsd256 dsd64..
And possibly link to thé actual track
Hence you Can test the qualit

Le ven. 13 sept. 2024, 14:00, Tim Curtis ***@***.***> a
écrit :

**Comment by moodeaudio** [comment]
Take a look at Quick help. Most of the info you are interested in can be obtained by simply searching the Library.
```
Predefined filters
The following predefined filters are available: Encoded [bits/rate | Nch | multichannel], Format [.ext], Folder [path], HDonly, Lossless, Lossy and Year [yyyy] or [yyyy-yyyy].

Examples: encoded 24/96 | encoded 192 | encoded 24 | encoded 6ch | encoded multichannel | hdonly | format .dsf | folder u2/achtung baby | lossy | year 1962 | year 1994-1998
```

If on the other hand you are proposing a new method for navigating or drilling into the Library then it becomes a substantial work effort that needs to be justified.

**Comment by jcor29** [comment]
Hi,
My idea is purely a suggestion.

Nevertheless, like most audiophile listen to the best recording
To be able to dig into your library, with in mind the best quality.
I have to browse my sacd folders to do it, i do it quite otten.

Having a search capability for it is a first step indeed, but not that
convenient i found.

I reckon for a non audiophile public, my idea

It remains  a suggestion and it i gather it will require a
substantial amount of work


Le ven. 13 sept. 2024 à 17:11, Tim Curtis ***@***.***> a
écrit :

**Comment by jcor29** [comment]
J Cornily ***@***.***>
17:52 (il y a 0 minute)
Répondre
À *moode-player/moode*


Sorry i haven't finished
Hi,
My idea is purely a suggestion.

Nevertheless, like most audiophile listen to the best recording
To be able to dig into your library, with in mind the best quality.
I have to browse my sacd folders to do it, i do it quite otten.

Having a search capability for it is a first step indeed, but not that
convenient i found.

I reckon for a non audiophile public, my idea has no sense
But for an audiophile public, i think it make sense to be able
to do it that way also

It remains  a suggestion and it i gather it will require a
substantial amount of work

Best Regards
Jacques

**Comment by monkeypox** [comment]
Can’t you just use the advanced search / saved search function to expose the file types you’re looking for?Sent from my iPhoneOn Sep 13, 2024, at 8:56 AM, jcor ***@***.***> wrote:﻿
J Cornily ***@***.***>

17:52 (il y a 0 minute)

Répondre

À *moode-player/moode*





Sorry i haven't finished

Hi,

My idea is purely a suggestion.



Nevertheless, like most audiophile listen to the best recording

To be able to dig into your library, with in mind the best quality.

I have to browse my sacd folders to do it, i do it quite otten.



Having a search capability for it is a first step indeed, but not that

convenient i found.



I reckon for a non audiophile public, my idea has no sense

But for an audiophile public, i think it make sense to be able

to do it that way also



It remains  a suggestion and it i gather it will require a

substantial amount of work



Best Regards

Jacques

**Comment by moodeaudio** [comment]
Will reopen if there is new information posted
