### ISSUE TITLE
a volume change should unmute 

### ISSUE THREAD

**Issue by lugdunum-1964** [moode-player/moode#684]
Normally on audio devices turning the volume up or down will switch mute off. Moode doesn't handle it this way. Currently, when one has used `vol.sh -mute` a consequent `vol.sh -up/-dn` will have no effect until another `vol.sh -mute` is sent.

adding:
```
VOLMUTE=0
sqlite3 $SQLDB "UPDATE cfg_system SET value='0' WHERE param='volmute'"
``` 
after line 115 should change this to a more intuitive behaviour.

--
regards, Lyon

**Comment by moodeaudio** [comment]
I'll test later today, thx.

**Comment by moodeaudio** [comment]
Here's the commit
[638ac80c](https://github.com/moode-player/moode/commit/638ac80c843e2c23600540117942675d6b6d1605)

**Comment by moodeaudio** [comment]
Completed
