### ISSUE TITLE
After push fwd key 2 times or more times sound is muted

### ISSUE THREAD

**Issue by yopmismo** [moode-player/moode#686]
When I'm playing songs from a playlist or disc using random, repeat and consume, after press fwd button two or more times the sound is muted but time elapse normally without reproduce sound. 
If I press pause and then play sound comes back.
I tried it reproducing a playlist and reproducing a disc, same issue.
This issue don't happen in version 8.

**Comment by moodeaudio** [comment]
Please post non-development issues in our Forum so all our users can benefit from the discussion.
Visit the Support page at moodeaudio.org for info on how to easily request a Forum account.
