### ISSUE TITLE
Player and Tag View height issue with bookmarks bar visible

### ISSUE THREAD

**Issue by tanathos** [moode-player/moode#687]
Hi, it looks like the height of the player and the Tag View is perfectly fitting a fullscreen browser (1080p) ONLY if the browser's bookmarks bar is not visible.
For people like me that keeps that always open the screens bottom part are out of the viewport, e.g.
![image](https://github.com/user-attachments/assets/ec9e0217-40a0-4a9a-93e1-6f5d4a7d7fd2)

While with the bookmarks bar closed I can see the bottom:
![image](https://github.com/user-attachments/assets/e417a31a-40cc-418e-8aa5-d92bce6bef23)

Same issue in the Tag View:
![image](https://github.com/user-attachments/assets/e2fd9fa4-8d61-4bb7-a253-72c911df33b9)

While I can see the tracks number without bookmarks bar:
![image](https://github.com/user-attachments/assets/59be75be-aa86-4fcd-98cb-cdcfd076f009)

In the Player is particularly annoying because it cuts off important action buttons.

I tested this with Chrome, Edge and Firefox, on a Windows 11 machine, same behavior.
Thanks!

**Comment by moodeaudio** [comment]
I'm trying to keep repo issues only for development related questions/problems.

Please report this to our Forum so all our users can benefit from the discussion. Visit the Support page at moodeaudio.org to easily request a Forum user account.
