### ISSUE TITLE
Spotify playback reset requently

### ISSUE THREAD

**Issue by thepartisan** [moode-player/moode#689]
Since a couple of weeks, I experience connection loss frequently when playing back via librespot.
The issue seems to be related with a known issue with [librespot: Connection reset by peer (os error 104)](https://github.com/librespot-org/librespot/issues/1340) which apparently will be (is?) fixed with librespot 0.5.0.

**Comment by moodeaudio** [comment]
Questions and troubleshooting are handled in the Support section of our Forum so that all our users can benefit from the discussion.

Visit the Support page at moodeaudio.org for information on how to easily request a Forum account.
