### ISSUE TITLE
No GUI when another system user was added

### ISSUE THREAD

**Issue by 59iosl30** [moode-player/moode#691]
Hello Tim!

When another (second) system user was created, the GUI did not appear. Looks like a bug ?

Workaround:
When the user's home directory was moved outside of /home, the GUI appeared again.

Kind regards,
Robert

**Comment by moodeaudio** [comment]
Questions and troubleshooting are handled in the Support section of our Forum so that all our users can benefit from the discussion.

Visit the Support page at moodeaudio.org for information on how to easily request a Forum account.
