### ISSUE TITLE
Possible copy/paste typo related to recently-added screensaver when playing feature

### ISSUE THREAD

**Issue by gbh-uk** [moode-player/moode#692]
I believe there is a possible copy/paste typo on line 1525 of www/templates/indextpl.html:

					<label class="control-label" for="auto-coverview">When playing</label>

The label's for parameter should be for="scnsaver-whenplaying"

**Comment by moodeaudio** [comment]
Thanks for the extra eyes :-)

I'll fix and push a commit later today.

**Comment by moodeaudio** [comment]
Fixed 7b26fb9
