### ISSUE TITLE
Question:  shell_execs

### ISSUE THREAD

**Issue by AlfredoCubitos** [moode-player/moode#697]
Hi, 
I found so many `shell_execs` in your code. 
Is there a special reason why you use `shell_exec` instead using internal php functions?
I think in some cases it would be faster to use native functions instead.

**Comment by moodeaudio** [comment]
No special reason, prolly just continuing with whatever the original sources had 12 years ago. 

Scanning the source tree it looks like 39 occurrences of "shell_exec" in 7 files. 

1. Which ones do you think should be replaced?
2. What is the exact code?

![Screenshot 2024-12-08 at 12 46 44 PM](https://github.com/user-attachments/assets/cc5a3429-d4fc-459a-9e46-af0fd1ce817a)

**Comment by AlfredoCubitos** [comment]
ah, ok. Thank you!
Do you have plans to switch from php to any other programming language?
I'm asking if  its still worthy to spend some lines of php code ;-)

**Comment by moodeaudio** [comment]
You mean rewrite the PHP codebase in some other programming language and convert to other framework libs. I don't see what could possibly justify such a massive and incredibly risky undertaking.

A quick count shows 61176 lines PHP and 5626 lines HTML for total __LOC = 66802__
```
pi@moode9:~ $ cd /var/www/
pi@moode9:/var/www $ find . -name '*.php' | xargs wc -l
     62 ./inp-config.php
    312 ./net-config.php
.
.
.
    338 ./command/queue.php
    165 ./command/cfg-table.php
    142 ./command/index.php
  61176 total
pi@moode9:/var/www $ 

pi@moode9:/var/www/templates $ find . -name '*.html' | xargs wc -l
   339 ./mpd-config.html
   495 ./snd-config.html
.
.
.
   190 ./lib-nas-config.html
    21 ./sys-status.html
  5626 total
```

**Comment by AlfredoCubitos** [comment]
I'm just asking to be sure.

Noo, a complete rewrite is too much, and not necessary.
But a few small improvements wouldn't hurt ;-)
Especially the thumb_nail generation and the samba connection need some work. On my Raspi 4 its very slow :-(
But I would appreciate if there is a different way to add changes  as by submitting a pull request ;-)

Btw, I found two possible issues in `thumb-gen.php`:
In line 77 and 78 you should use `ls -d ` to get only directories. 
This is by the way one reason to use php native functions :-)

**Comment by moodeaudio** [comment]
I'm always interested in improvements but its best to submit a tested PR and then I'll have a look at the code changes.
