### ISSUE TITLE
Provide PINN image

### ISSUE THREAD

**Issue by phobos-dev** [moode-player/moode#93]
Hi,

would it be possible to provide an PINN image for integration in that project. This way one could easily install moOde in a multi OS environment. Also it would help to get the project greater and widely spread around the globe. Would be great.

Thanks for considering.

References:
https://github.com/procount/pinn
procount/pinn#358

**Comment by moodeaudio** [comment]
Not possible. moOde it tightly integrated into it's own custom version of Raspbian Lite called MoodeOS.

**Comment by procount** [comment]
MoOde v7.6.1 has now been converted for installation using PINN.
If you are interested in maintaining PINN images for future versions of moOde, please get in touch.

**Comment by lurch** [comment]
Just to clarify, PINN is an OS-installer (so you'd use it to install MoodeOS), it's not an application installer :slightly_smiling_face:
