### ISSUE TITLE
Audio via HDMI

### ISSUE THREAD

**Issue by stelgenhof** [moode-player/moode#94]
Is it possible to have the audio output via HDMI? In the configuration the HDMI port is set to on, however I can't see how I can configure this.

Cheers! Sacha

**Comment by moodeaudio** [comment]
Theres no configuration for HDMI, you just plug in the cable and Raspbian automatically switches from the 3.5mm RCA port to the HDMI port. Just make sure on MPD Config its set to use On-board audio.

**Comment by stelgenhof** [comment]
Thanks! The settings seem to be correct (On-board audio), however let me check once more tomorrow.

**Comment by stelgenhof** [comment]
It's working fine. I feel so stupid: volume was set to zero, haha. Thanks for the great software!
