### ISSUE TITLE
Do you plan tu integrate multiroom solution?

### ISSUE THREAD

**Issue by zenman94** [moode-player/moode#98]
Do you plan to integrate a tool like  snapcast for multiroom ?

**Comment by moodeaudio** [comment]
I was experimenting with an audio distribution system based on the TRX project but I was never able to debug it. http://www.pogo.org.uk/~mark/trx/

Charlie Laub's GASysCon system is another avenue I'd like to explore at some point.

Ideally though, sync multiroom should be implemented as an integrated MPD plugin. Maybe a dev will someday create one.

**Comment by zenman94** [comment]
Thanks for this reply. 
I will test LMS and squeezlite to start my  multiroom deployment.
